<?php
echo "<div style='width:340px;text-align:center;color:#0046AD'>";
echo "<h3>Product Categories</h3>";
foreach ($this->Catalog->getTopCategories() as $Category)
{
    $Image = $Category->getImages()->first();
    
    $image = $Image ? 
		$Image->getSize("150", "100")->getHtml() : 
		"<div style='width:150px;height:100px;vertical-align:center;text-align:center'>no image</div>";
    
    echo "<div style='float:left;margin:8px;width:150px;'>";
    echo "<a href='/category/".$Category->getIndex()."'>";
    echo $image;
	echo "<div style='height:30px;'>";
	    echo $Category->getName()."</div></div>";
}

echo "<div style='clear:both'></div>";
echo "</div>";