<?php
foreach ($this->Catalog->getProducts() as $Product)
{
    $Image = $Product->getImages()->first();
    
    $image = $Image ? 
		$Image->getSize("248", "180")->getHtml() : 
		"<div style='width:248px;height:180px;vertical-align:center;text-align:center'>no image</div>";
    
    echo "<div style='float:left;margin:8px;width:248px;'>".$image.$Product->getName()."</div>";
}

echo "<div style='clear:both'></div>";