<div style="margin: 35px;margin-top: 0px;">
    <h2 style="color: #0092ef;">
	Contact Us
    </h2>
    <hr></hr>
    <div style="padding:30px;">
	<div style="float: left;">
	    <span style="color: #0092ef;font-weight: 600;">Main Office</span>
	    <p>Texwin Carports<br />
	    1501 Goodnight Blvd.<br />
	    Wills Point, TX<br />
	    Phone: (800) 636-4700<br />
	    E-Mail: info@texwincarports.com</p>
	</div>
	<img src="<?php echo BASE_URL;?>/img/texwin/contactus.jpg" style="float: right;"/>
	<div style="clear: both;"></div>
	<div>
	    <?php echo $this->form;?>
	</div>
    </div>
</div>