<?php 
use Dataservice\Html\CRUD;

echo($this->flashMessages()); 

echo CRUD\Header::factory("Time Clock - View")->getHtml();

$Menu = $this->Menu;

CRUD\Body::factory()->start();

CRUD\Tabs::factory()
	->addEntityViewTab("Information", $Menu)
	->addRelationshipViewTab($Menu, "Website")
	->addRelationshipViewTab($Menu, "Items")
	->render();

CRUD\Body::factory()->end();

echo CRUD\Tabs::factory()->getJS();