<div style="padding:30px;">
    <h2 style="color: #0092ef;">Who is Texwin?</h4>
    <hr></hr>
    <div style="padding: 25px;padding-top: 0px;">
	<p>
	    <img src="<?php echo BASE_URL;?>/img/texwin/logo_basic_small.png" alt="Texwin Logo" style="vertical-align: top; display: inline;float: left;margin: 15px;margin-left: 0px;"/>
	    Texwin is a family owned and operated manufacturer of high quality carports, garages, barns, and many other styles of 
	    metal dwellings and coverings. Our main office is Located in Wills Point, Tx and we have many retailers throughout Texas.
	    We strive for excellence everyday to provide you with the best carport structure for the money in a timely and courteous fashion.
	    Give us a chance to will see the Texwin difference.
	</p>
	<p>
	    Feel free to contact us <a href="/index/contactus" >here</a> for any questions you may have or to order yours!
	</p>
	<img src="<?php echo BASE_URL;?>/img/texwin/home/carports.png" alt="carports" style="width: 600px;"/>
	<p>
	    We have many <a href="/locations" >retail locations</a> you can visit as well today.
	</p>
    </div>
</div>