<div style="margin: 35px;margin-top: 0px;">
    <h2 style="color: #0092ef;">
	Financing
    </h2>
    <hr></hr>
    <div style="padding: 50px;padding-top: 0px;padding-bottom: 0px;">
	<img src="<?php echo BASE_URL;?>/img/texwin/piggybank.jpg" style="float: left;width: 100px;vertical-align: top;margin-right: 10px;" />
	<br />
	Our suppliers have a multitude of finance options to make purchasing our products easier for everyone.
	From rent to own, bank financing, and multiple payment medium options it has never been easier to purchase a Texwin structure!
	Each dealers policies are different and subject to their own financing terms.
    </div>
    <br />
	<p>
	    Feel free to contact us <a href="/index/contactus" >here</a> for any questions you may have or to order yours!
	</p>
	<img src="<?php echo BASE_URL;?>/img/texwin/home/carports.png" alt="carports" style="width: 600px;"/>
	<p>
	    We have many <a href="/locations" >retail locations</a> you can visit as well today.
	</p>
</div>