<style type="text/css">
    #quality_control_list li{
	padding-top: 0px;
	vertical-align: top;
    }
</style>
<div style="margin: 35px;margin-top: 0px;">
    <h2 style="color: #0092ef;">
	Quality Control
    </h2>
    <hr></hr>
    <img src="<?php echo BASE_URL;?>/img/texwin/home/approved.png" style="width: 400px;"/>
    <h4>Our Quality Control  Objectives:</h4>

    <ul id="quality_control_list" style="list-style: url('<?php echo BASE_URL;?>/img/texwin/bullet_check.jpg');color: #0052CC;font-size: 15px;margin:35px;margin-top: 0px;">
	<li>
	    To deliver our clients the standards of quality specified in the contract within budget.
	</li>
	<li>
	    To create and maintain a culture of quality within the group.
	</li>
	<li>
	    To ensure that all our employees are trained in quality assurance and that this training is ongoing at all levels.
	</li>
	<li>
	    To meet all legal requirements.
	</li>
	<li>
	    To provide the resources necessary to achieve the required level of quality.
	</li>
	<li>
	    To ensure that quality control mechanisms are being sufficiently and effectively applied at all times.
	</li>
	<li>
	    To provide documentary evidence of all quality control measures.
	</li>
	<li>
	    To ensure that all consultants, suppliers, sub-contractors and others who are involved in our projects meet the required quality standards.
	</li>
	<li>
	    To continually review, improve and implement quality control and best practice procedures.
	</li>
	<li>
	    To seek feedback from our clients and consultants as to the level of quality delivered.
	</li>
    </ul>
    <p>
	Feel free to contact us <a href="/index/contactus" >here</a> for any questions you may have or to order yours!
    </p>
    <img src="<?php echo BASE_URL;?>/img/texwin/home/carports.png" alt="carports" style="width: 600px;"/>
    <p>
	We have many <a href="/locations" >retail locations</a> you can visit as well today.
    </p>
</div>