<div style="margin: 35px;margin-top: 0px;">
    <h2 style="color: #0092ef;">
	Why should I choose Texwin?
    </h2>
    <hr></hr>
    <img src="<?php echo BASE_URL;?>/img/texwin/home/checklist.jpg"  style="width:200px;float: left;"/>
    <ul style="list-style: circle;color: #0052CC;font-size: 15px;margin:35px;">
	<li>Automatically backed by our 25 Year Rust Perforation Warranty</li>
	<li>Fire resistant</li>
	<li>Stronger than traditional steel building structures</li>
	<li>7 times more rust resistant than regular steel</li>
	<li>Excellent for heat reflectivity</li>
	<li>Easy to assemble and best construction value per square foot</li>
	<li>Built on your level site for you or an ideal DIY project geared at virtually any skill level.</li>
    </ul>
    <div style="padding: 30px;padding-top: 20px;padding-bottom: 15px;">
	&nbsp;&nbsp;We cover more than 2,000,000 square feet (every year) with metal buildings and carports,
    we have any option you're looking for, along with the name and brand you can trust. When you order a
    product a product from us, you’re dealing with a local family business you can trust not some distant
    national corporation who is not in touch with your needs. We encourage you to check out the company you
    deal with before purchasing, A great way to do that is google 'carport scams'
    <a href="http://www.google.com/search?q=carport+scams">here</a>
    or other search terms, this will at least tell you who NOT to deal with. Texwin carports Inc. Built to last!
    
    
	<p>
	    Feel free to contact us <a href="/index/contactus" >here</a> for any questions you may have or to order yours!
	</p>
	<img src="<?php echo BASE_URL;?>/img/texwin/home/carports.png" alt="carports" style="width: 600px;"/>
	<p>
	    We have many <a href="/locations" >retail locations</a> you can visit as well today.
	</p>
    </div>
</div>
