<?php 
use Dataservice\Html\CRUD;

echo($this->flashMessages()); 
echo CRUD\Header::factory("Rto Provider Fee Percentage - View")->getHtml();

$Percentage = $this->Percentage;

$crudBody = new CRUD\Body();

$crudBody->start();

$Tabs = CRUD\Tabs::factory();

$Tabs->addEntityViewTab("Information", $Percentage)
	->addRelationshipViewTab($Percentage, "RtoProvider")
	->addRelationshipViewTab($Percentage, "Programs")
	->render();

$crudBody->end();

echo $Tabs->getJS();
