    <div id="winslows-layout-footer-content-container">
        <div id="footer-div-1">
            <a href='http://www.facebook.com/WinslowsBuildings?fref=ts'><img src="/img/winslows/layout/news_img.png" /></a >
        </div>
    
    <div id="footer-div-2">
            <a href='http://www.facebook.com/WinslowsBuildings?fref=ts'><img src="/img/winslows/layout/place_holder.png" /></a >
		    
<!--        <div id="our-partners-links-footer">
            <a href='http://www.facebook.com/WinslowsBuildings?fref=ts'><img src="/img/winslows/layout/texwin.png" /></a>
            <a href='http://twitter.com/winslowssales'><img src="/img/winslows/layout/lonestar.png" /></a>
        </div>-->
<!--        <div id="social-media-links-footer">
            <a href='http://www.facebook.com/WinslowsBuildings?fref=ts'><img src="/img/winslows/layout/fb_icon_img.png" /></a>
            <a href='http://twitter.com/winslowssales'><img src="/img/winslows/layout/twt_icon_img.png" /></a>
            <a href='http://mike-winslowscarportsandstorage.blogspot.com/'><img src="/img/winslows/layout/blogt_icon_img.png" /></a><br>
        </div>-->
    </div>
    <div id="footer-div-3">
            <ul class="font-main-blue font-kalinga"> 
                <li><a style ="color: blue;" class="font-main-blue font-kalinga" href='#'>Contact Us</a></li>
                <li><a style ="color: blue;" class="font-main-blue font-kalinga"href='#'>Locations</a></li>
                <li><a style ="color: blue;" class="font-main-blue font-kalinga"href='#'>About Us</a></li>
                <li><a style ="color: blue;" class="font-main-blue font-kalinga"href='#'>Gallery</a></li>
                <li><a style ="color: blue;" class="font-main-blue font-kalinga"href='#'>Company Policies</a></li>
                <li><a style ="color: blue;" class="font-main-blue font-kalinga"href='#'>Mailing List</a></li>
            </ul>
    </div>
    </div>
