<!DOCTYPE>
<html>
<head>
    <?php 
    echo $this->headTitle();
    
    $this->headLink()->prependStylesheet('/css/winslows/layout.css');
    $this->headLink()->prependStylesheet('/css/global.css');
    $this->headLink()->prependStylesheet('/css/winslows/layout/global2.css');
    $this->headLink()->prependStylesheet('/css/winslows/layout/menu.css');
    echo $this->headLink();
    
    echo $this->headMeta();
    $this->headScript()->prependFile('/javascript/common.js');
    $this->headScript()->prependFile('/javascript/jquery/jquery.js');
    $this->headScript()->appendFile('/javascript/winslows/layout.js');
    
    echo $this->headScript();
    ?>
</head>
<body>
    <div id="layout_main">
	<div id="layout_content">
	    <div id="winslows-layout-header-logo-container">
		<a href='http://www.facebook.com/WinslowsBuildings?fref=ts'><img src="/img/winslows/layout/logo.png" /></a >
		<div id="body-links">
		    <ul class="font-kalinga">
			<li><a href='#'><span>Log In</span></a></li>
			<li><a href='#'><span>Contact Us</span></a></li>
			<li><a href='#'><span>Shopping Cart</span></a></li>
		    </ul>
		</div>
		    <div id="get-started-button-img">
			<a href='http://www.facebook.com/WinslowsBuildings?fref=ts'><img src="/img/winslows/layout/get_started_button.png" /></a >
		    </div>
		<div id="winslows-layout-header-contact-info">
		    <p class="font-kalinga">Phone: (800) 636-4700</p>
		</div>
	    </div>
	    <div id="winslows-layout-header-content-container">
		<div id="menu_container">
		    <div id='cssmenu'>
			<?php
			    $MenuBuilder    = \Classes\Menu::factory();
			    $Website	    = Services\Website::factory()->getCurrentWebsite();
			    $Menu	    = $Website->getMenuByIndex("menu_navigation");
			    $MenuHTMLObject = $MenuService->getMenuHTML($MenuBuilder, $Menu);
			    
			    $Menu->attrs = array(
				"class"	=> "drop_menu"
			    );
			    
			    echo $Menu->render();
			?>
		    </div>
		    <div id="search-bar">
			<img src="/img/winslows/layout/searchbar.png" />
		    </div>
		</div>
	    </div>
	    <div id="winslows-layout-content">
		<?php
		    echo $this->layout()->content;
		?>
	    </div>
	</div>
    </div>
    <div id="winslows-layout-footer">
	<?php
	    echo $this->partial("footer.phtml");
	?>
    </div>
</body>
</html>
