<!DOCTYPE>
<html>
<head>
    <?php 
    echo $this->headTitle();
    
    $this->headLink()->prependStylesheet('/css/winslows/layout.css');
    $this->headLink()->prependStylesheet('/winslows/global.css');
     $this->headLink()->prependStylesheet('/winslows/global2.css');
    echo $this->headLink();
    
    echo $this->headMeta();
    $this->headScript()->prependFile('/javascript/common.js');
    $this->headScript()->prependFile('/javascript/jquery/jquery.js');
    $this->headScript()->appendFile('/javascript/winslows/layout.js');
    
    echo $this->headScript();
    ?>
        <div id="header-logo">
            <img src="/img/winslows/layout/logo.png" />
        </div>
</head>
<body>
    <div id="winslows-layout-header-container">
        <div id="winslows-layout-header-img">
            <img src="/img/winslows/layout/header_img.png" />
        </div>
        <div id='cssmenu'>
            <ul>
               <li class='active '>
               <li><a href='#'><span>Home</span></a></li>
               <li><a href='#'><span>Services</span></a></li>
               <li><a href='#'><span>Products</span></a></li>
               <li><a href='#'><span>Gallery</span></a></li>
               <li><a href='#'><span>Locations</span></a></li>
               <li><a href='#'><span>Contact Us</span></a></li>
            </ul>
        </div>
    </div>
    <div id="winslows-layout-main">
        <div id='body-links'>
            <ul>
               <font face= "Kalinga" size= "2">
               <a href='#'><span>Services</span></a>          
               <a href='#'><span>Products</span></a>          
               <a href='#'><span>My Account</span></a>
               <a href='#'><span>Gallery</span></a>
               <a href='#'><span>Locations</span></a>
               <a href='#'><span>Contact Us</span></a>
               <a href='#'><span>About Us</span></a>
               </font>
            </ul>
        </div>
    </div>
    <div>
        <?php
        echo $this->layout()->content 
        ?>
    </div>
        
</body>
</html>
