<?php 
use Dataservice\Html\CRUD;

echo($this->flashMessages()); 

echo CRUD\Header::factory("Website Resource - View")->getHtml();

$Resource = $this->Resource;

CRUD\Body::factory()->start();

CRUD\Tabs::factory()
	->addEntityViewTab("Information", $Resource)
	->addRelationshipViewTab($Resource, "Website")
	->addRelationshipViewTab($Resource, "Roles")
	->render();

CRUD\Body::factory()->end();

echo CRUD\Tabs::factory()->getJS();