<?php echo($this->flashMessages()); ?>
<fieldset class="padded_frame blue_frame">
    <legend>ACL Resources</legend>
    <?php
    /* @var $Resource \Entities\Company\Website\Resource */
    foreach($this->Resources as $Resource){
	echo "<div resource_id='".$Resource->getId()."'>";
	echo \Dataservice\Html\Button::buttonIcon(
		"pencil.png", 
		"editresource_".$Resource->getId(), 
		"Edit Resource", 
		"edit_resource", 
		"padding-right:5px;"
		);
	echo ":: ";
	echo $Resource->getName();
	$Roles = $Resource->getRoles();
	if(count($Roles)<1)echo " <span class='messenger_error'>!! No Roles !! </span>";
	echo " <span class='gray small'>".$Resource->getCreated()->format("m:d:Y")."</span>";
	echo "</div>";
    }
    ?>
</fieldset>
<script type="text/javascript">
    Resource = new Resource();
    Resource.EditOnclickBind($(".edit_resource"));
</script>