<?php 
echo($this->flashMessages()); 
echo "<div>";
echo HTML::backAnchorIcon("Suppliers - All", "/supplier/viewall");
echo "</div>";
?>
<h1 class="header1">Supplier - View</h1>
<?php
/* @var $Supplier \Entities\Supplier */
$Supplier	= $this->Supplier;
$supplier_id	= $Supplier->getId();
$Companies	= $Supplier->getCompanies();
$Products	= $Supplier->getProducts();
$Addresses	= $Supplier->getSupplierAddresses();
?>
<div class="blue_frame bg_blue_fade" style="margin: 20px;margin-bottom: 0px;padding: 5px;">
    <h3 class="no_space" style="color: #2000EE;">
	Info
	<?php
	echo HTML::anchorIcon(
		"pencil.png", 
		"", 
		"/supplier/edit/id/".$supplier_id,
		"margin-left:5px;"
		);
	?>
    </h4>
    <div>
	Name: <?php echo $Supplier->getName(); ?> &nbsp;&nbsp;&nbsp;
    </div>
</div>
<div class="padded_frame" style="width: 415px;float: left;padding-top: 0px;">
    <div id="accordion">
	<h3>
	    <a href="#">Address</a>
	    <?php echo HTML::buttonBlue("building_add.png", "Add Address", "address_add", "float:right;width:110px;");?>
	</h3>
	<div>
	    <?php
	    /* @var $Address \Entities\Address */
	    foreach ($Addresses as $Address) {
		?>
		<h4 class="no_space bg_blue_fade blue_frame" style="padding: 3px;margin-bottom: 3px;">
		    <?php 
		    echo $Address->getName();
		    echo HTML::anchorIcon(
			    "pencil.png", 
			    "", 
			    "/supplieraddress/edit/supplier_id/".$supplier_id."/id/".$Address->getId(),
			    "margin-left:5px;"
			    );
		    ?>
		</h4>
		<label>Address 1:</label>
		<div style="display: inline;"><?php echo $Address->getAddress1(); ?></div><br />
		<label>Address 2:</label>
		<div style="display: inline;"><?php echo $Address->getAddress2(); ?></div><br />
		<label>City/ST/Zip:</label>
		<div style="display: inline;">
		    <?php 
		    echo $Address->getCity().", ".
			    $Address->getState()." ".
			    $Address->getZip1()."-".
			    $Address->getZip2(); ?>
		</div>
		<?php
	    }
	    ?>
	</div>
	<hr />
	<h3>
	    <a href="#">Companies</a>
	    <?php echo HTML::buttonBlue("building_add.png", "Add Company", "company_add", "float:right;width:110px;");?>
	</h3>
	<div>
	    <?php
	    /* @var $Company \Entities\Company */
	    if(count($Companies)>0){
		foreach ($Companies as $Company) {
		    ?>
		    <div style="padding: 3px;margin-bottom: 3px;">
			<?php 
			echo $Company->getName();
			echo HTML::anchorIcon(
				"building_go.png", 
				"", 
				"/company/view/id/".$Company->getId(),
				"margin-left:5px;"
				);
			?>
		    </div>
		    <?php
		}
	    }
	    else echo "No Companies";
	    ?>
	</div>
	<hr />
    </div>
</div>
<div class="padded_frame" style="width: 415px;float: right;padding-top: 0px;">
    <h3>
	<a href="#">Products</a>
	<?php echo HTML::buttonBlue("package_add.png", "Add Product", "product_add", "float:right;width:110px;");?>
    </h3>
    <div>
	<?php
	/* @var $Product \Entities\Product */
	if(count($Products)>0){
	    foreach ($Products as $Product) {
		?>
		<div style="padding: 3px;margin-bottom: 3px;">
		    <?php 
		    echo $Product->getName();
		    echo HTML::anchorIcon(
			    "package_go.png", 
			    "", 
			    "/product/view/id/".$Product->getId(),
			    "margin-left:5px;"
			    );
		    ?>
		</div>
		<?php
	    }
	}
	else echo "No Products";
	?>
    </div>
    <hr />
    <h3><a href="#">Documents</a></h3>
    <div>Put Documents here</div>
</div>
<div style="clear: both;"><input type="hidden" id="supplier_id" value="<?php echo $supplier_id;?>" /></div>
<script type="text/javascript">
    Supplier = new Supplier();
    Supplier.AddAddressOnclickBind($("#address_add"));
    Supplier.AddCompanyOnclickBind($("#company_add"));
    Supplier.AddProductOnclickBind($("#product_add"));
</script>
