<?php 
use Dataservice\Html\CRUD;

echo($this->flashMessages()); 

echo CRUD\Header::factory("Image Resized Clone - View")->getHtml();

$ResizedClone = $this->ResizedClone;

CRUD\Body::factory()->start();

CRUD\Tabs::factory()
	->addTab(
	    CRUD\Tabs\Tab::factory("Information")
		->addEntityView($ResizedClone)
		->addContent($ResizedClone->getHtmlImage()->setStyle("margin:25px;width:100px;")->getHtml())
	)
	->addRelationshipViewTab($ResizedClone, "Image")
	->render();

CRUD\Body::factory()->end();

echo CRUD\Tabs::factory()->getJS();