<?php 
use Dataservice\Html\CRUD;

echo($this->flashMessages()); 

echo CRUD\Header::factory("Supplier - View")->getHtml();

$Supplier   = $this->Supplier;
$Tabs	    = CRUD\Tabs::factory();

CRUD\Body::factory()->start();

$Tabs->addEntityViewTab("Information", $Supplier)
	->addRelationshipViewTab($Supplier, "Company")
	->addTab(
	    CRUD\Tabs\Tab::factory(("Contact Info"))
		->addRelationshipView($Supplier, "Addresses")
	);

$Tab = CRUD\Tabs\Tab::factory("Products");

$relationshipContent = CRUD\Content\Relationship\OneToMany::factory($Supplier, "Products");

$relationshipContent->addHtmlHeaderContent($relationshipContent->relationshipPropertyName);
$relationshipContent->addHtmlHeaderContent(
	\Dataservice\Html\Anchor::addIcon(
		"Configurable", 
		"/supplier-product-configurable/edit/id/0/supplier_id/".$relationshipContent->parentEntity->getId(), 
		"Add Configurable Product"
		)
	);
$relationshipContent->addHtmlHeaderContent(
	\Dataservice\Html\Anchor::addIcon(
		"Simple", 
		"/supplier-product-simple/edit/id/0/supplier_id/".$relationshipContent->parentEntity->getId(), 
		"Add Simple Product"
		)
	);
$relationshipContent->buildRelationshipBodyHtml();

$Tab->addContent($relationshipContent->getHtml());

$Tabs->addTab($Tab);

$Tabs->render();

CRUD\Body::factory()->end();

echo CRUD\Tabs::factory()->getJS();