<?php echo($this->flashMessages()); ?>
<h1 class="header1">Suppliers - View All</h1>
<fieldset class="padded_frame blue_frame">
    <legend>Menu</legend>
    <?php
    echo HTML::buttonBlue("add.png", "Add Supplier", "add_supplier", "position:relative;");
    ?>
</fieldset>
<fieldset class="padded_frame blue_frame">
    <legend>Suppliers</legend>
    <?php
    /* @var $Supplier \Entities\Company\Supplier */
    foreach($this->Suppliers as $Supplier){
	echo "<div supplier_id='".$Supplier->getId()."'>";
	echo HTML::buttonIcon(
		"magnifier.png", 
		"editsupplier_".$Supplier->getId(), 
		"Edit Supplier", 
		"edit_supplier", 
		"padding-right:5px;"
		);
	echo ":: ";
	echo $Supplier->getName();
    }
    ?>
</fieldset>
<script type="text/javascript">
    Supplier = new Supplier();
    Supplier.AddOnclickBind($("#add_supplier"));
    Supplier.EditOnclickBind($(".edit_supplier"));
</script>