<div id="content-info-container">
    <ul class="content-info-container-font-style">
        <h1>No credit check financing  ****   Rent to own options</h1>
        <h3>NO credit check</h3>
        <a> You can have a convenient and appealing building, even with credit issues.</a>
        <br>
        <h3>Instant approval</h3>
        <a>You wont wait on a finance company. You can have the building as soon as we can deliver it.</a>
        <br>
        <h3>Rent-to-own storage</h3>
        <a>You can own your storage building in 36 months. You will own your own storage and will never 
        pay rent again for an inaccessible unit across town.</a> 
        <br>
        <h3>Credit Card Options</h3>
        <a>Ability to use credit cards for the deposit and initial payment
        You can purchase a building without cash-in-hand. You can also build up your credit earnings.</a>
        <br>                                                                              
        <h3>Early Purchase Option (EPO) Discount</h3>
        <a>You are not penalized for paying early. In fact, paying early saves money.</a>
    </ul>
</div>