<?php echo($this->flashMessages()); ?>
<h1 class="header1">Companies - View All</h1>
<fieldset class="padded_frame blue_frame">
    <legend>Menu</legend>
    <?php
    echo \Dataservice\Html\Button::buttonBlue("add.png", "Add Company", "add_company", "position:relative;");
    ?>
</fieldset>
<fieldset class="padded_frame blue_frame">
    <legend>Companies</legend>
    <?php
    /* @var $Company \Entities\Company */
    foreach($this->Companys as $Company){
	echo "<div company_id='".$Company->getId()."'>";
	echo \Dataservice\Html\Button::buttonIcon(
		"bullet_go.png", 
		"editcompany_".$Company->getId(), 
		"Edit Company", 
		"edit_company", 
		"padding-right:5px;"
		);
	echo ":: ";
	echo $Company->getName()." - ".$Company->getDba();
    }
    ?>
</fieldset>
<script type="text/javascript">
    Company = new Company();
    Company.AddOnclickBind($("#add_company"));
    Company.EditOnclickBind($(".edit_company"));
</script>