<?php 
use Dataservice\Html\CRUD;

echo($this->flashMessages()); 
echo CRUD\Nav::factory("Dashboard", "index/index")->getHtml();
echo CRUD\Header::factory("Company - View")->getHtml();

/* @var $Company \Entities\Company */
$Company	= $this->Company;

$crudBody = CRUD\Body::factory();
$crudTabs = CRUD\Tabs::factory();

$crudBody->start();

$crudTabs->addEntityViewTab("Information", $Company);

$crudTabs->addCollectionListTabs(array(
    array("Leads", $Company, "Leads"),
    array("Locations", $Company, "Locations"),
    array("Employees", $Company, "Employees"),
    array("Suppliers", $Company, "Suppliers"),
    array("Rto Providers", $Company, "RtoProviders"),
    array("Dealers", $Company, "Dealers"),
    array("Websites", $Company, "Websites"),
));

$crudTabs->render();

$crudBody->end();

echo $crudTabs->getJS();
