<?php 
use Dataservice\Html\CRUD;

echo($this->flashMessages()); 

echo CRUD\Header::factory("Company - View")->getHtml();

/* @var $Company \Entities\Company */
$Company	= $this->Company;

CRUD\Body::factory()->start();
CRUD\Tabs::factory()
	->addEntityViewTab("Information", $Company)
	->addRelationshipViewTab($Company, "Leads")
	->addRelationshipViewTab($Company, "Locations")
	->addRelationshipViewTab($Company, "Employees")
	->addRelationshipViewTab($Company, "Suppliers")
	->addRelationshipViewTab($Company, "RtoProviders")
	->addRelationshipViewTab($Company, "Dealers")
	->addRelationshipViewTab($Company, "Websites")
	->render();

CRUD\Body::factory()->end();

echo CRUD\Tabs::factory()->getJS();
