<?php
$category	= $this->product['category'];
$styles		= $this->product['styles'];
$applications	= $this->product['applications'];
$accessories	= $this->product['accessories'];
$images		= $this->product['images'];
?>
<div style="width:700px;">
    <h3 style="color: #0092ef;padding-top: 0px;padding-bottom: 0px;margin-bottom: 0px;margin-top: 0px;"><?php echo $category['categories_summary'];?></h3>
    <hr />
    <div>
	<div class="view_main_image">
	    
	</div>
	<div class="view_thumbs">
	    
	</div>
    </div>
</div>