<?php echo($this->flashMessages()); ?>
<fieldset class="padded_frame blue_frame">
    <legend>Websites</legend>
    <?php
    /* @var $Resource \Entities\Company\Website */
    foreach($this->Websites as $Website)
    {
	echo "<div website_id='".$Website->getId()."'>";
	echo HTML::buttonIcon(
		"bullet_go.png", 
		"view_website_".$Website->getId(), 
		"View Website", 
		"view_website", 
		"padding-right:5px;"
		);
	
	echo ":: ";
	echo $Website->getName();
	echo "</div>";
    }
    ?>
</fieldset>
<script type="text/javascript">
    Website = new Website();
    Website.ViewOnclickBind($(".view_website"));
</script>