<?php 
use Dataservice\Html\CRUD;

echo($this->flashMessages()); 

echo CRUD\Header::factory("Dealer Location Fax Number - View")->getHtml();

$FaxNumber = $this->FaxNumber;

CRUD\Body::factory()->start();

CRUD\Tabs::factory()
	->addEntityViewTab("Information", $FaxNumber)
	->addRelationshipViewTab($FaxNumber, "Location")
	->addRelationshipViewTab($FaxNumber, "Contacts")
	->render();

CRUD\Body::factory()->end();

echo CRUD\Tabs::factory()->getJS();