<?php 
use Dataservice\Html\CRUD;

echo($this->flashMessages()); 

echo CRUD\Header::factory("Dealer Location - View")->getHtml();

/* @var $Location \Entities\Company\Dealer\Location */
$Location	= $this->Location;

CRUD\Body::factory()->start();

CRUD\Tabs::factory()
	->addEntityViewTab("Information", $Location)
	->addRelationshipViewTab($Location, "Dealer")
	->addRelationshipViewTab($Location, "Address")
	->addRelationshipViewTab($Location, "PhoneNumber")
	->addRelationshipViewTab($Location, "FaxNumber")
	->render();

CRUD\Body::factory()->end();

echo CRUD\Tabs::factory()->getJS();