<div style="padding: 10px;">
    Code: <input type="text" id="test" size="100" /><br />
    State: <input type="text" id="state" size="2" /><br />
    <input id="test_button" type="button" value="Submit"/>
</div>
<div style="padding: 10px;" id="result"></div>
<script type="text/javascript">
    $(document).ready(function() {
	$("#test_button").click(function(){
	    $.ajax({
		data: {
			code:$("#test").val(),
			state: $("#state").val()
		    },
		dataType: 'html',
		type: "GET",
		url: '/test/codetohtml',
		success: function(data) {
		    $('#result').html(data);
		}
	    });
	});
    });
</script>