<?php 
echo($this->flashMessages()); 
echo HTML::backAnchorIcon("Employee - View", "/employee/view/id/".$this->Employee->getId());
?>
<h1 class="header1">Employee - Manage Roles</h1>
<fieldset class="padded_frame blue_frame center">
    <legend>Edit '<?php echo $this->Employee->getFullName(); ?>' Roles</legend>
    <input type="hidden" id="employee_id" value="<?php echo $this->Employee->getId();?>" />
    <?php
    echo $this->form;
    ?>
    <ul>
    <?php
    $Roles = $this->Employee->getRoles();
    
    if(count($Roles)>0){
	/* @var $Role \Entities\Company\Employee\Role */
	foreach($Roles as $Role)
	{
	    echo "<li role_id='".$Role->getId()."'>".
		    HTML::buttonIcon(
			    "delete.png", 
			    "delete_role", 
			    "Remove Role", 
			    "remove_role", 
			    "padding-right:5px;"
			    ).
		    $Role->getName().
		    "</li>";
	}
    }
    else echo "<li>No roles assigned</li>";
    ?>
    </ul>
</fieldset>
<script type="text/javascript">
    Company_Employee_Role = new Company_Employee_Role();
    Company_Employee_Role.FormSubmit();
    Company_Employee_Role.RemoveRoleOnclickBind($(".remove_role"));
</script>