<?php 
use Dataservice\Html\CRUD;

echo($this->flashMessages()); 
echo CRUD\Header::factory("Employee - View")->getHtml();

/* @var $Employee \Entities\Company\Employee */
$Employee	= $this->Employee;

$crudBody = new CRUD\Body();

$crudBody->start();

$Tabs = CRUD\Tabs::factory();

$Tabs->addEntityViewTab("Information", $Employee)
    ->addTab(
	CRUD\Tabs\Tab::factory(("Contact Info"))
	    ->addRelationshipView($Employee, "PhoneNumbers")
	    ->addRelationshipView($Employee, "FaxNumbers")
	    ->addRelationshipView($Employee, "Addresses")
	    ->addRelationshipView($Employee, "EmailAddresses")
    )
    ->addRelationshipViewTab($Employee, "Company")
    ->addRelationshipViewTab($Employee, "Location")
    ->addRelationshipViewTab($Employee, "Account")
    ->render();

$crudBody->end();

echo $Tabs->getJS();
