<?php 
use Dataservice\Html\CRUD;

echo($this->flashMessages()); 

echo CRUD\Header::factory("Website Role - View")->getHtml();

$Role = $this->Role;

CRUD\Body::factory()->start();

CRUD\Tabs::factory()
	->addEntityViewTab("Information", $Role)
	->addRelationshipViewTab($Role, "Website")
	->addRelationshipViewTab($Role, "Accounts")
	->addRelationshipViewTab($Role, "Resources")
	->render();

CRUD\Body::factory()->end();

echo CRUD\Tabs::factory()->getJS();