<?php 
use Dataservice\Html\CRUD;

echo($this->flashMessages()); 
echo CRUD\Header::factory("Rto Provider Program View")->getHtml();

$Program = $this->Program;

$crudBody = new CRUD\Body();

$crudBody->start();

$Tabs = CRUD\Tabs::factory();

$Tabs->addEntityViewTab("Information", $Program)
	->addRelationshipViewTab($Program, "RtoProvider")
	->addRelationshipViewTab($Program, "Products")
	->addRelationshipViewTab($Program, "Fees")
	->render();

$crudBody->end();

echo $Tabs->getJS();
