<?php echo $this->localHeader();?>
<h4 style="color: #0052CC;">
    <?php echo $this->selected 
	    ? "<input type='button' id='size_next' value='next >>'/>" 
	    : "Add a door to your building.";
    ?>
</h4>
<div id="builder_doors_form" class="form_div">
    <form id="doors_form" name="doors_form" method="POST">
	<div style="font-weight:600;padding:0px;padding-left:0px;line-height: 30px; ">Door Type:</div>
	<img class="colorpicker_images" src="/img/builder/door_types_1.png" alt="door types" title="Door types" style="margin: 0px;padding: 0px;"border="0" usemap="#doors_map" />
	<div style="text-align: center;" id="size_utility" style="display: none;">
	    <div style="font-weight:600;padding:0px;padding-left:0px;line-height: 30px;text-align: left;">Size:</div><br />
	    <input class="doors_form" type="radio" value="32X72" id="size_3272" name="size" /><label for="size_3272">&nbsp;&nbsp;&nbsp;32"X72"&nbsp;&nbsp;&nbsp;</label>
	    <input class="doors_form" type="radio" value="36X80" id="size_3680" name="size" /><label for="size_3680">&nbsp;&nbsp;&nbsp;36"X80"&nbsp;&nbsp;&nbsp;</label>
	</div>
	<div style="text-align: center;" id="size_rollup" style="display: none;">
	    <div style="font-weight:600;padding:0px;padding-left:0px;line-height: 30px;text-align: left;">Size:</div><br />
	    <input class="doors_form" type="radio" value="6X6" id="size_66" name="size" /><label for="size_66">&nbsp;&nbsp;&nbsp;6'X6'&nbsp;&nbsp;&nbsp;</label>
	    <input class="doors_form" type="radio" value="8X8" id="size_88" name="size" /><label for="size_88">&nbsp;&nbsp;&nbsp;8'X8'&nbsp;&nbsp;&nbsp;</label>
	    <input class="doors_form" type="radio" value="9X8" id="size_98" name="size" /><label for="size_98">&nbsp;&nbsp;&nbsp;9'X8'&nbsp;&nbsp;&nbsp;</label>
	    <input class="doors_form" type="radio" value="9X10" id="size_108" name="size" /><label for="size_108">&nbsp;&nbsp;&nbsp;10'X8'&nbsp;&nbsp;&nbsp;</label>
	    <input class="doors_form" type="radio" value="10X10" id="size_1010" name="size" /><label for="size_1010">&nbsp;&nbsp;&nbsp;10'X10'&nbsp;&nbsp;&nbsp;</label>
	</div>
	<div style="text-align: center;" id="location_radios">
	    <input type="hidden" value="" id="door_type" name="type"/>
	    <div style="font-weight:600;padding:0px;padding-left:0px;line-height: 30px;text-align: left;">Location on Building:</div><br />
	    <input class="doors_form" type="radio" value="L" id="location_l" name="location" /><label for="location_l">&nbsp;&nbsp;&nbsp;Left&nbsp;&nbsp;&nbsp;</label>
	    <input class="doors_form" type="radio" value="R" id="location_r" name="location" /><label for="location_r">&nbsp;&nbsp;&nbsp;Right&nbsp;&nbsp;&nbsp;</label>
	    <input class="doors_form" type="radio" value="F" id="location_f" name="location" /><label for="location_f">&nbsp;&nbsp;&nbsp;Front&nbsp;&nbsp;&nbsp;</label>
	    <input class="doors_form" type="radio" value="B" id="location_b" name="location" /><label for="location_b">&nbsp;&nbsp;&nbsp;Back&nbsp;&nbsp;&nbsp;</label>
	</div>
	<input type="button" style="width:200px;text-align: center;margin-left: 95px;margin-top: 20px;" value="Add" id="door_add" />
	<map id="doors_map" name="doors_map" class="tabs">
	<!-- #$-:Image map file created by GIMP Image Map plug-in -->
	<!-- #$-:GIMP Image Map plug-in by Maurits Rijk -->
	<!-- #$-:Please do not edit lines starting with "#$" -->
	<!-- #$VERSION:2.3 -->
	<!-- #$AUTHOR:Jessie -->
	<area shape="rect" coords="36,8,187,103" alt="Roll Up Garage Door" target="rollup"  nohref="nohref" code="RU"/>
	<area shape="rect" coords="219,9,356,102" alt="Outswing Utility Door" target="utility"  nohref="nohref" code="OS"/>
	</map>
    </form>
</div>
<h4 style="color: #0052CC;">
    <?php echo "Remove a door from your building";
    ?>
</h4>
<?php
if(count($this->doors)>0){
    echo "<table>";
    foreach ($this->doors as $number => $door) {
	echo "<tr>";
	echo "<td>".HTML::buttonIcon("delete.png", $number, "Delete", "current_doors_list", "")." </td><td>".
		$door["display_num"]."</td><td> - ".$door["location"]."</td><td> - ".$door["size"]."</td><td> - ".
		$door["type"]."</td>";
	echo "</tr>";
    }
    echo "</table>";
}
else echo "No Doors Added Yet"
?>
<script type="text/javascript">
$('#size_next').button();
$('#size_next').click(function(){
    $("#example").tabs("select" , "Walls" );
});

b = new Builder();
b.doors_init();
b.update('<?php echo $this->code;?>','<?php echo $this->price;?>',<?php echo $this->hints;?>, <?php echo json_encode($this->details);?>, <?php echo json_encode($this->price_details);?>);
</script>
