<h4 style="color: #0052CC;">
    <?php echo $this->selected 
	    ? "<input type='button' id='model_next' value='next >>'/>" 
	    : "Choose the model of building you would like.";
    ?>
</h4>
<div>
    <?php
	echo $this->form;
	if($this->selected){
	    ?>
	    
	    <?php
	}
    ?>
</div>
<script type="text/javascript">
$('#model_next').button();
$('#model_next').click(function(){
    $("#example").tabs("select" , "Size" );
});

b = new Builder();
b.model_click_bind();
b.update('<?php echo $this->code;?>','<?php echo $this->price;?>',<?php echo $this->hints;?>,<?php echo json_encode($this->details);?>, <?php echo json_encode($this->price_details);?>);
</script>
