<?php echo $this->localHeader;?>
<h4 style="color: #0052CC;">
    <?php echo $this->selected 
	    ? "<input type='button' id='model_next' value='next >>'/>" 
	    : "Choose the model of building you would like.";
    ?>
</h4>
<div id="model_form_cont">
    <img src="/img/builder/types.png" style="width: 350px;height: 80px;"/>
    <?php
	echo $this->form;
    ?>
</div>
<script type="text/javascript">
$('#model_next').button();
$('#model_next').click(function(){
    $("#example").tabs("select" , "Size" );
});
$( "#model_form_cont" ).buttonset();
b = new Builder();
b.model_click_bind();
</script>
<?php echo $this->localFooter();?>
