<?php echo $this->localHeader();?>
<h4 style="color: #0052CC;">
    <?php echo $this->selected 
	    ? "<input type='button' id='size_next' value='next >>'/>" 
	    : "Choose the size of building you would like.";
    ?>
</h4>
<script type="text/javascript">
    $(function() {
	$( ".form_div" ).buttonset();
    });
</script>
<div>
    <?php
	echo $this->form;
    ?>
</div>
<script type="text/javascript">
$('#size_next').button();
$('#size_next').click(function(){
    $("#example").tabs("select" , "Walls" );
});

b = new Builder();
b.size_click_bind();
</script>
<?php echo $this->localFooter();?>
