<h4 style="color: #0052CC;">
    <?php echo $this->selected 
	    ? "<input type='button' id='type_next' value='next >>'/>" 
	    : "Choose the type of building you would like.";
    ?>
</h4>
<div>
    <?php
	echo $this->form;
    ?>
</div>
<script type="text/javascript">
$('#type_next').button();
$('#type_next').click(function(){
    $("#example").tabs("select" , "Model" );
});

b = new Builder();
b.type_click_bind();
b.update('<?php echo $this->code;?>','<?php echo $this->price;?>', <?php echo $this->hints;?>, <?php echo json_encode($this->details);?>, <?php echo json_encode($this->price_details);?>);
</script>
