<?php echo $this->localHeader();?>
<h4>
    <?php echo $this->selected 
	    ? "<input type='button' id='type_next' value='next >>'/>" 
	    : "Choose the type of building you would like.";
    ?>
</h4>
<div id="type_form_cont">
    <?php
	echo $this->form;
    ?>
</div>
<script type="text/javascript">
$('#type_next').button();
$('#type_next').click(function(){
    $("#example").tabs("select" , "Model" );
});
$("#type_form_cont").buttonset();

b = new Builder();
b.type_click_bind();
</script>
<?php echo $this->localFooter();?>
