<?php echo $this->localHeader();?>
<h4 style="color: #0052CC;">
    <?php echo $this->selected 
	    ? "<input type='button' id='size_next' value='next >>'/>" 
	    : "Add a window to your building.";
    ?>
</h4>
<div id="builder_windows_form" class="form_div">
    <form id="windows_form" name="windows_form" method="POST">
	<div style="text-align: center;" id="window_location_radios">
	    <input type="hidden" value="SA" id="window_type" name="type"/>
	    <input type="hidden" value="30X30" id="window_size" name="size"/>
	    <div style="font-weight:600;padding:0px;padding-left:0px;line-height: 30px;text-align: left;">Location on Building:</div><br />
	    <input class="windows_form" type="radio" value="L" id="windows_location_l" name="location" /><label for="windows_location_l">&nbsp;&nbsp;&nbsp;Left&nbsp;&nbsp;&nbsp;</label>
	    <input class="windows_form" type="radio" value="R" id="windows_location_r" name="location" /><label for="windows_location_r">&nbsp;&nbsp;&nbsp;Right&nbsp;&nbsp;&nbsp;</label>
	    <input class="windows_form" type="radio" value="F" id="windows_location_f" name="location" /><label for="windows_location_f">&nbsp;&nbsp;&nbsp;Front&nbsp;&nbsp;&nbsp;</label>
	    <input class="windows_form" type="radio" value="B" id="windows_location_b" name="location" /><label for="windows_location_b">&nbsp;&nbsp;&nbsp;Back&nbsp;&nbsp;&nbsp;</label>
	</div>
	<input type="button" style="width:200px;text-align: center;margin-left: 95px;margin-top: 20px;" value="Add" id="window_add" />
    </form>
</div>
<h4 style="color: #0052CC;">
    <?php echo "Remove a window from your building";
    ?>
</h4>
<?php
if(count($this->windows)>0){
    echo "<table>";
    foreach ($this->windows as $number => $window) {
	echo "<tr>";
	echo "<td>".HTML::buttonIcon("delete.png", $number, "Delete", "current_windows_list", "")." </td><td>".
		$window["display_num"]."</td><td> - ".$window["location"]."</td><td> - ".$window["size"]."</td><td> - ".
		$window["type"]."</td>";
	echo "</tr>";
    }
    echo "</table>";
}
else echo "No Windows Added Yet"
?>
<script type="text/javascript">
$('#size_next').button();
$('#size_next').click(function(){
    $("#example").tabs("select" , "Walls" );
});

b = new Builder();
b.windows_init();
</script>
<?php echo $this->localFooter();?>
