<?php 
echo($this->flashMessages()); 
echo "<div>";
echo HTML::backAnchorIcon("Configurable Product Option Parameter - All", "/company/supplier-product-configurable-option-parameter/viewall");
echo "</div>";
?>
<h1 class="header1">Configurable Product Option Parameter - View</h1>
<?php
/* @var $Parameter \Entities\Company\Supplier\Product\Configurable\Option\Parameter */
$Parameter	= $this->Parameter;
$parameter_id	= $Parameter->getId();
$Values		= $Parameter->getValues();
$Option		= $Parameter->getOption();
?>
<div class="blue_frame bg_blue_fade" style="margin: 20px;margin-bottom: 0px;padding: 5px;">
    <h4 class="no_space" style="color: #2000EE;">
	Info
	<?php
	echo HTML::anchorIcon(
		"pencil.png", 
		"", 
		"/company/supplier-product-configurable-option-parameter/edit/id/".$parameter_id,
		"margin-left:5px;",
		"Edit Option",
		"option_edit"
		);
	?>
    </h4>
    <div>
	<label>Id:</label> <?php echo $Parameter->getId(); ?> &nbsp;&nbsp;&nbsp;
	<label>Name:</label> <?php echo $Parameter->getName(); ?> &nbsp;&nbsp;&nbsp; 
	<label>Index:</label> <?php echo $Parameter->getIndex(); ?> &nbsp;&nbsp;&nbsp;
	<label>Length:</label> <?php echo $Parameter->getLength(); ?>  &nbsp;&nbsp;&nbsp;
	<label>Required:</label> <?php echo $Parameter->isRequiredString(); ?> <br /> 
	<label>Description:</label> <span class="small"><?php echo $Parameter->getDescription(); ?></span>
    </div>
</div>
<div class="padded_frame" style="width: 415px;float: left;padding-top: 0px;">
    <div id="accordion">
	<h3>
	    <a href="#">Option</a>
	</h3>
	<div>
	    <ul>
	    <?php
	    /* @var $Option \Entities\Company\Supplier\Product\Configurable\Option */
	    if($Option){
		?>
		<li>
		    <?php
		    echo HTML::anchorIcon(
			    "magnifier.png", 
			    "", 
			    "/company/supplier-product-configurable-option/view/id/".$Option->getId(),
			    "margin-left:5px;"
			    );
		    echo $Option->getName();
		    ?>
		</li>
		<?php
	    }
	    else echo "<li>No Option Assigned</li>";
	    ?>
	    </ul>
	</div>
	<hr />
	<h3>
	    <a href="#">Values</a>
	    <?php 
	    echo HTML::buttonBlue(
		    "bullet_add.png", 
		    "Add New", 
		    "value_add", 
		    "float:right;width:80px;"
		    );
	    ?>
	</h3>
	<div>
	    <ul>
	    <?php
	    /* @var $Value \Entities\Company\Supplier\Product\Configurable\Option\Parameter\Value */
	    if(count($Values)>0)
	    {
		foreach ($Values as $Value)
		{
		    ?>
		    <li>
			<?php
			echo HTML::anchorIcon(
				"pencil.png", 
				"", 
				"/company/supplier-product-configurable-option-parameter-value/edit/id/".
				    $Value->getId(),
				"margin-left:5px;",
				"Edit Value"
				);
			echo $Value->getName();
			?>
		    </li>
		    <?php
		}
	    }
	    else echo "<li>No Values</li>";
	    ?>
	    </ul>
	</div>
	<hr />
    </div>
</div>
<div class="padded_frame" style="width: 415px;float: right;padding-top: 0px;">
    <h3><a href="#">Documents</a></h3>
    <div>Put Documents here</div>
</div>
<div style="clear: both;"><input type="hidden" id="parameter_id" value="<?php echo $parameter_id;?>" /></div>
<script type="text/javascript">
    Parameter = new Parameter();
    Parameter.ValueAddOnclickBind($("#value_add"));
</script>
