<?php echo($this->flashMessages()); ?>
<h1 class="header1">Configurable Product Option Parameter - View All</h1>
<fieldset class="padded_frame blue_frame">
    <legend>Menu</legend>
    <?php
    echo HTML::buttonBlue("add.png", "Add Parameter", "parameter_add", "position:relative;");
    ?>
</fieldset>
<fieldset class="padded_frame blue_frame">
    <legend>Parameters</legend>
    <?php
    /* @var $Parameter \Entities\Company\Supplier\Product\Configurable\Option\Parameter */
    foreach($this->Parameters as $Parameter){
	echo "<div parameter_id='".$Parameter->getId()."'>";
	echo HTML::buttonIcon(
		"magnifier.png", 
		"parameter_view_".$Parameter->getId(), 
		"View Parameter", 
		"parameter_view", 
		"padding-right:5px;"
		);
	echo HTML::buttonIcon(
		"delete.png", 
		"parameter_delete_".$Parameter->getId(), 
		"Delete Parameter", 
		"parameter_delete", 
		"padding-right:5px;"
		);
	echo ":: ";
	echo $Parameter->getName()."<span class='gray small'> - ".
		$Parameter->getOption()->getName()."</span>";
    }
    ?>
</fieldset>
<script type="text/javascript">
    Parameter = new Parameter();
    Parameter.AddOnclickBind($("#parameter_add"));
    Parameter.ViewOnclickBind($(".parameter_view"));
    Parameter.DeleteOnclickBind($(".parameter_delete"));
</script>