<?php 
echo($this->flashMessages()); 
$this->CRUD_Header("Lead - View");
/* @var $lead \Entities\Company\Lead */
$Lead		= $this->Lead;
$Addresses	= $Lead->getAddresses();
$PhoneNumbers	= $Lead->getPhoneNumbers();
$EmailAddresses	= $Lead->getEmailAddresses();
$Contacts	= $Lead->getContacts();
$Quotes		= $Lead->getQuotes();
$Applications	= $Lead->getApplications();
$Anchor		= new \Dataservice\Html\Anchor;

$this->CRUD_Body()->start();
$this->CRUD_Tabs()->headers(array("Info", "Contact", "Quote", "Rto"));
?>
<div id="Info">
    <h4>
	Information
    </h4>
    <ul>
	<li>
	    <?php
	    echo $Anchor->editIcon("", "/lead/edit/id/".$Lead->getId(), "Edit Lead");
	    echo $Anchor->deleteIcon("", "/lead/delete/id/".$Lead->getId(), true, "Delete Lead");
	    echo htmlspecialchars($Lead->toString());
	    ?>
	</li>
    </ul>
</div>
<div id="Contact">
    <h4>
	Addresses
	<?php
	echo $Anchor->addIcon("", "/lead-address/edit/id/0/lead_id/".$Lead->getId(), "Add Address");
	?>
    </h4>
    <ul>
    <?php	
    if(!$Addresses->count())echo "<li>No addresses</li>";
    else
	foreach ($Addresses as $Address)
	{
	    echo "<li>";
	    echo $Anchor->editIcon("", "/lead-address/edit/id/".$Address->getId(), "Edit Address");
	    echo $Anchor->deleteIcon("", "/lead-address/delete/id/".$Address->getId(), true, "Delete Address");
	    echo htmlspecialchars($Address->toString());
	    echo "</li>";
	}
    ?>
    </ul>
    <h4>
	Phone Numbers
	<?php
	echo $Anchor->addIcon("", "/lead-phone-number/edit/id/0/lead_id/".$Lead->getId(), "Add Phone Number");
	?>
    </h4>
    <ul>
    <?php	
    if(!$PhoneNumbers->count())echo "<li>No phone numbers</li>";
    else
	foreach ($PhoneNumbers as $PhoneNumber)
	{
	    echo "<li>";
	    echo $Anchor->editIcon("", "/lead-phone-number/edit/id/".$PhoneNumber->getId(), "Edit Phone Number");
	    echo $Anchor->deleteIcon("", "/lead-phone-number/delete/id/".$PhoneNumber->getId(), true, "Delete Phone Number");
	    echo htmlspecialchars($PhoneNumber->toString());
	    echo "</li>";
	}
    ?>
    </ul>
    <h4>
	Email Addresses
	<?php
	echo $Anchor->addIcon("", "/lead-email-address/edit/id/0/lead_id/".$Lead->getId(), "Add Email Address");
	?>
    </h4>
    <ul>
    <?php	
    if(!$EmailAddresses->count())echo "<li>No email addresses</li>";
    else
	foreach ($EmailAddresses as $EmailAddress)
	{
	    echo "<li>";
	    echo $Anchor->editIcon("", "/lead-email-address/edit/id/".$EmailAddress->getId(), "Edit Email Address");
	    echo $Anchor->deleteIcon("", "/lead-email-address/delete/id/".$EmailAddress->getId(), true, "Delete Email Address");
	    echo htmlspecialchars($EmailAddress->toString());
	    echo "</li>";
	}
    ?>
    </ul>
</div>
<div id="Quote">
    <h4>Quotes</h4>
    <ul>
    <?php	
    if(!$Quotes->count())echo "<li>No Quotes</li>";
    else
	foreach ($Quotes as $Quote)
	{
	    echo "<li>";
	    echo $Anchor->viewIcon("", "/lead-quote/view-sales/id/".$Quote->getId(), "View Quote");
	    echo htmlspecialchars($Quote->toString());
	    echo "</li>";
	}
    ?>
    </ul>
</div>
<div id="Rto">
    <h2>Coming Soon</h2>
</div>
<?php
$this->CRUD_Body()->end();