<?php 
use Dataservice\Html\CRUD;

echo($this->flashMessages()); 
echo CRUD\Header::factory("Lead - View")->getHtml();

/* @var $Lead \Entities\Company\Lead */
$Lead	    = $this->Lead;
$crudBody   = new CRUD\Body();

$crudBody->start();

$Tabs = CRUD\Tabs::factory();

$Tabs->addEntityViewTab("Information", $Lead)
    ->addRelationshipViewTab($Lead, "Company")
    ->addRelationshipViewTab($Lead, "Employee")
    ->addTab(
	CRUD\Tabs\Tab::factory(("Contact Info"))
	    ->addRelationshipView($Lead, "PhoneNumbers")
	    ->addRelationshipView($Lead, "FaxNumbers")
	    ->addRelationshipView($Lead, "Addresses")
	    ->addRelationshipView($Lead, "EmailAddresses")
    )
    ->addRelationshipViewTab($Lead, "Quotes")
    ->addRelationshipViewTab($Lead, "Applications")
    ->addRelationshipViewTab($Lead, "Account")
    ->render();

$crudBody->end();

echo $Tabs->getJS();
