<?php 
echo($this->flashMessages()); 
echo "<div>";
echo \Dataservice\Html\Anchor::backAnchorIcon("Company - View", "/index/view/id/".$this->Lead->getCompany()->getId());
echo "</div>";
?>
<h1 class="header1">Lead - View</h1>
<?php
/* @var $lead \Entities\Company\Lead */
$lead		= $this->Lead;
$lead_id	= $lead->getId();
$addresses	= $lead->getAddresses();
$phones		= $lead->getPhoneNumbers();
$emails		= $lead->getEmailAddresses();
$contacts	= $lead->getContacts();
$quotes		= $lead->getQuotes();
$Applications	= $lead->getApplications();
?>
<div class="blue_frame bg_blue_fade" style="margin: 20px;margin-bottom: 0px;padding: 5px;">
    <h4 class="no_space" style="color: #2000EE;">
	Info
	<?php
	echo \Dataservice\Html\Anchor::anchorIcon(
		"pencil.png", 
		"", 
		"/lead/edit/id/".$lead_id,
		"margin-left:5px;"
		);
	?>
    </h4>
    <div>
	Name:<?php echo $lead->getFullName(); ?> &nbsp;&nbsp;&nbsp;
	Company:<?php echo $lead->getEmployee()->getLocation()->getCompany()->getName(); ?> &nbsp;&nbsp;&nbsp; 
	Salesman:<?php echo $lead->getEmployee()->getFullName(); ?>
    </div>
</div>
<div class="padded_frame" style="width: 415px;float: left;padding-top: 0px;">
    <div id="accordion">
	<h3>
	    <a href="#">Addresses</a>
	    <?php echo \Dataservice\Html\Button::buttonBlue("add.png", "Add address", "address_add", "float:right;width:110px;");?>
	</h3>
	<div>
	    <?php
	    echo count($addresses)<1 ? "<span class='small gray'>No Addresses</span>" : "";
	    /* @var $Address \Entities\Company\Address */
	    foreach ($addresses as $Address) {
		?>
		<h4 class="no_space bg_blue_fade blue_frame" style="padding: 3px;margin-bottom: 3px;">
		    <?php 
		    echo $Address->getName();
		    echo \Dataservice\Html\Anchor::anchorIcon(
			    "pencil.png", 
			    "", 
			    "/lead-address/edit/person_id/".$lead_id."/id/".$Address->getId(),
			    "margin-left:5px;"
			    );
		    ?>
		</h4>
		<label for="addr_1_addr1">Address 1:</label>
		<div id="addr_1_addr1" style="display: inline;"><?php echo $Address->getAddress1(); ?></div><br />
		<label for="addr_1_addr2">Address 2:</label>
		<div id="addr_1_addr2" style="display: inline;"><?php echo $Address->getAddress2(); ?></div><br />
		<label for="addr_1_csz">City/ST/Zip:</label>
		<div id="addr_1_csz" style="display: inline;">
		    <?php 
		    echo $Address->getCity().", ".
			    $Address->getState()." ".
			    $Address->getZip1()."-".
			    $Address->getZip2(); ?>
		</div>
		<?php
	    }
	    ?>
	</div>
	<hr />
	<h3>
	    <a href="#">Phone</a>
	    <?php 
	    echo \Dataservice\Html\Button::buttonBlue(
		    "phone_add.png", 
		    "Add Phone", 
		    "phone_add", "float:right;width:110px;"
		    );?>
	</h3>
	<div>
	    <?php
	    echo count($phones)<1 ? "<span class='small gray'>No Phones</span>" : "";
	    /* @var $PhoneNumber \Entities\Company\Person\PhoneNumber */
	    foreach ($phones as $PhoneNumber)
	    {
		?>
		<h4 class="no_space blue_frame bg_blue_fade" style="padding:3px;margin-bottom: 3px;">
		    <?php 
		    echo $PhoneNumber->getType(); 
		    echo \Dataservice\Html\Anchor::anchorIcon(
			    "pencil.png", 
			    "", 
			    "/lead-phone-number/edit/person_id/".$lead_id."/id/".
				$PhoneNumber->getId(), 
			    "margin-left:5px;"
			    );
		    ?>
		</h4>
		<label for="phone1">Num:</label>
		<div id="phone1" style="display: inline;">
		    <?php 
		    echo "(".$PhoneNumber->getAreaCode().") ".$PhoneNumber->getNum1()."-".$PhoneNumber->getNum2(); 
		    ?>
		</div><br />
		<label for="ext1">Ext:</label>
		<div id="ext1" style="display: inline;">
		    <?php 
		    echo $PhoneNumber->getExtension(); 
		    ?>
		</div>
		<?php
	    }
	    ?>
	</div>
	<hr />
	<h3>
	    <a href="#">Email</a>
	    <?php 
	    echo \Dataservice\Html\Button::buttonBlue(
		    "email_add.png", 
		    "Add Email", 
		    "email_add", "float:right;width:110px;"
		    );?>
	</h3>
	<div>
	    <?php
	    /* @var $Emailaddress \Entities\Emailaddress */
	    foreach ($emails as $Emailaddress) {
		?>
		<h4 class="no_space bg_blue_fade blue_frame" style="padding: 3px;margin-bottom: 3px;">
		    <?php 
		    echo $Emailaddress->getType(); 
		    echo \Dataservice\Html\Anchor::anchorIcon(
			    "pencil.png", 
			    "", 
			    "/person/email-address/edit/person_id/".$lead_id."/id/".
				$Emailaddress->getId(), 
			    "margin-left:5px;"
			    );
		    ?>
		</h4>
		<label>Address:</label>
		<div style="display: inline;">
		    <?php 
		    echo $Emailaddress->getAddress(); 
		    ?>
		</div>
		<?php
	    }
	    ?>
	</div>
	<hr />
	<h3>
	    <a href="#">Rto Applications</a>
	</h3>
	<div>
	    <?php
	    /* @var $Application \Entities\Company\RtoProvider\Application */
	    foreach ($Applications as $Application)
	    {
		?>
		<div style="padding: 3px;margin-bottom: 3px;">
		    <?php 
		    echo $Application->getRtoProvider()->getDba();
		    echo \Dataservice\Html\Anchor::anchorIcon(
			    "bullet_go.png", 
			    "", 
			    "/rto-provider-application/edit/id/".$Application->getId(),
			    "margin-left:5px;"
			    );
		    ?>
		</div>
		<?php
	    }
	    ?>
	</div>
	<hr />
    </div>
</div>
<div class="padded_frame" style="width: 415px;float: right;padding-top: 0px;">
    <h3>
	<a href="#">Quotes</a>
	<span style="float:right;">
	    <?php 
	    echo \Dataservice\Html\Button::buttonBlue(
		    "money_add.png", 
		    "Add Quote", 
		    "quote_add", 
		    "quote_add", 
		    "padding-left:3px;"
		    );?>
	</span>
    </h3>
    <div>
	<div style="max-height: 300px;overflow: auto;">
	    <?php
	    /* @var $Quote \Entities\Company\Lead\Quote */
	    if(count($quotes)>0)
	    {
		foreach ($quotes as $Quote)
		{
		    ?>
		    <h4 class="no_space bg_blue_fade blue_frame" style="padding:3px;margin-bottom: 3px;">
			<?php 
			echo $Quote->getCreated()->format("m-d-Y, g:i a"); 
			echo \Dataservice\Html\Anchor::anchorIcon(
				"bullet_go.png", 
				"", 
				"/lead-quote/view/id/".
				    $Quote->getId(), 
				"margin-left:5px;"
				);
			?>
		    </h4>
		    <label>Total:</label>
		    <div style="display: inline;">
			<?php 
			echo $Quote->getTotal()->getDisplayPrice();
			?>
		    </div><br />
		    <label>Number Of Products:</label>
		    <div style="display: inline;">
			<?php 
			echo $Quote->getTotalItemsQuantity();
			?>
		    </div><br /><br />
		    <?php
		}
	    }
	    else echo "No quotes.";
	    ?>
	</div>
    </div>
    <hr />
    <h3>
	<a href="#">Contacts</a>
	<span style="float:right;">
	    <?php 
	    echo \Dataservice\Html\Button::buttonBlue(
		    "phone_sound.png", 
		    "Add Contact", 
		    "contact_add", 
		    "contact_add", 
		    "padding-left:3px;"
		    );?>
	</span>
    </h3>
    <div>
	<div style="max-height: 300px;overflow: auto;">
	    <?php
	    /* @var $Contact \Entities\Company\Lead\Contact */
	    foreach ($contacts as $Contact) {
		?>
		<h4 class="no_space bg_blue_fade blue_frame" style="padding:3px;margin-bottom: 3px;">
		    <?php 
		    echo $Contact->getCreated()->format("m-d-Y, g:i a"); 
		    echo \Dataservice\Html\Anchor::anchorIcon(
			    "pencil.png", 
			    "", 
			    "/lead-contact/edit/lead_id/".$lead_id."/id/".
				$Contact->getId(), 
			    "margin-left:5px;"
			    );
		    ?>
		</h4>
		<label>By:</label>
		<div style="display: inline;">
		    <?php 
		    echo $Contact->getEmployee()->getFirstName();
		    ?>
		</div><br />
		<label>Type:</label>
		<div style="display: inline;">
		    <?php 
		    echo $Contact->getTypeDisplay()." - ".$Contact->getTypeDetail(); 
		    ?>
		</div><br />
		<label>Note:</label>
		<div style="display: inline;">
		    <?php 
		    echo \Dataservice\String::truncate($Contact->getNote(), 40);
		    ?>
		</div><br />
		<label>Result:</label>
		<div style="display: inline;">
		    <?php 
		    echo $Contact->getResultDisplay();
		    ?>
		</div><br /><br />
		<?php
	    }
	    ?>
	</div>
    </div>
    <hr />
    <h3><a href="#">Documents</a></h3>
    <div>Put Documents here</div>
</div>
<div style="clear: both;"><input type="hidden" id="lead_id" value="<?php echo $lead_id;?>" /></div>
<script type="text/javascript">
    Lead = new Lead();
    Lead.AddPhoneClickBind("phone_add");
    Lead.AddAddressClickBind("address_add");
    Lead.AddEmailClickBind("email_add");
    Lead.AddContactClickBind("contact_add");
    Lead.AddQuoteClickBind("quote_add");
</script>
