<?php echo $this->localHeader();?>
<h4>
    Choose Wall Options <br /><span style="color:silver;font-size: 12px;"> (Required if you want any doors, windows, etc.).</span>
</h4>
<div style="clear: both;">
    <?php
	echo $this->form;
    ?>
    <div style="clear: both;"></div>
</div>
<script type="text/javascript">
$('#walls_next').button();
$('#walls_next').click(function(){
    $("#example").tabs("select" , "Colors" );
});
$( ".jquery_radio" ).buttonset();
b = new Builder();
b.walls_click_bind();
</script>
<?php echo $this->localFooter();?>
