<?php echo($this->flashMessages()); ?>
<fieldset class="padded_frame blue_frame">
    <legend>Menu</legend>
<?php
echo HTML::buttonBlue("company_add.png", "Add Company", "company_add", "position:relative;");
?>
</fieldset>
<fieldset class="padded_frame blue_frame">
    <legend>Companies</legend>
    <ol>
    <?php
    /* @var $Company \Entities\Company */
    foreach($this->companies as $Company){
	echo "<li>";
	echo HTML::anchorIcon(
		    "building_add.png", 
		    "", 
		    "/maintenance/locationadd/id/".$Company->getId(),
		    "margin-right:3px;"
		);
	echo $Company->getName();
	$locations = $Company->getLocations();
	if(count($locations)>0){
	    echo "<ul>";
	    foreach($locations as $Location){
		echo "<li>".$Location->getName()."</li>";
	    }
	    echo "<ul>";
	}
	echo "</li>";
    }
    ?>
    </ol>
</fieldset>
<script type="text/javascript">
    Company = new Company();
    Company.AddOnclickBind($("#menuitem_add"));
    Company.EditOnclickBind($(".menuitem_edit"));
    Company.AddChildOnclickBind($(".child_add"));
    Company.RemoveOnclickBind($(".menuitem_remove"));
</script>