<?php echo($this->flashMessages()); ?>
<fieldset class="padded_frame blue_frame">
    <legend>Menu</legend>
<?php
echo HTML::buttonBlue("group_add.png", "Add Group", "group_add", "position:relative;");
?>
</fieldset>
<fieldset class="padded_frame blue_frame">
    <legend>Groups</legend>
    <ol>
    <?php
    /* @var $role \Entities\Role */
    foreach($this->roles as $role){
	?>
	<li class="padded_frame" group_id="<?php echo $role->getId();?>"> 
	    <?php 
	    echo HTML::buttonIcon("group_edit.png", "group_edit", "Edit Group Details", "group_edit", "padding-right:5px;");
	    echo HTML::buttonIcon("key_add.png", "group_privilege_add", "Add Privilege to Group", "group_privilege_add", "padding-right:5px;");
	    echo HTML::buttonIcon("key_go.png", "group_privilege_show", "Show Privileges", "group_privilege_show", "padding-right:5px;");
	    echo $role->getName();
	    ?>
	    <span class="gray small"><?php echo HTML::truncateString($role->getDescription(), 200);?></span>
	    <fieldset id="privileges_container_<?php echo $role->getId();?>" class="blue_frame padded_frame" style="display: none;">
		<legend>Privileges:</legend>
		    <?php
		    /* @var $privilege \Entities\Privilege */
		    $privileges = $role->getPrivileges();
		    if($privileges && count($privileges) > 0){
			?><ol><?php
			foreach ($privileges as $privilege) {
			    ?>
			    <li privilege_id="<?php echo $privilege->getId();?>">
				<?php 
				echo HTML::buttonIcon("key.png", "privilege_edit", "Edit Privilege", "privilege_edit", "padding-right:5px;");
				echo HTML::buttonIcon("key_delete.png", "privilege_delete", "Delete Privilege", "privilege_delete", "padding-right:5px;");
				echo $privilege->getName();
				?>
			    </li>
			    <?php
			}
			?></ol><?php
		    }
		    else{
			echo " None";
		    }
		    ?>
	    </fieldset>
	</li>
	<?php
    }
    ?>
    </ol>
</fieldset>
<script type="text/javascript">
    Group = new Group();
    Group.AddOnclickBind($("#group_add"));
    Group.EditOnclickBind($(".group_edit"));
    Group.AddPrivilegeOnclickBind($(".group_privilege_add"));
    Group.ShowPrivilegeOnclickBind($(".group_privilege_show"));
    Group.EditPrivilegeOnclickBind($(".privilege_edit"));
    Group.DeletePrivilegeOnclickBind($(".privilege_delete"));
</script>