<?php
$important_links = array(
    array(
        "link"      => "/buy-online/index",
        "image"     => "icon_buy.png",
        "header"    => "Buy Online"
    ),
    array(
        "link"      => "/pricing/index",
        "image"     => "icon_pricing.png",
        "header"    => "Pricing"
    ),
    array(
        "link"      => "/build_yours/index",
        "image"     => "icon_build.png",
        "header"    => "Build Yours"
    ),
    array(
        "link"      => "/inventory/index",
        "image"     => "icon_inventory.png",
        "header"    => "Inventory"
    ),
    array(
        "link"      => "/gallery/index",
        "image"     => "icon_gallery.png",
        "header"    => "Gallery"
    ),
    array(
        "link"      => "/locations/index",
        "image"     => "icon_locations.png",
        "header"    => "Locations"
    ),
    array(
        "link"      => "/used_repos/index",
        "image"     => "icon_repos.png",
        "header"    => "Used/Repos"
    ),
    array(
        "link"      => "/financing/index",
        "image"     => "icon_finance.png",
        "header"    => "Financing"
    )
);

echo $this->partialLoop("/index/important-links-loop.phtml", $important_links);
