<?php 
echo($this->flashMessages()); 
//echo HTML::backAnchorIcon("Employees View", "/maintenance/employeesview");
?>
<h1 class="header1">Web Account - Roles</h1>
<fieldset class="padded_frame blue_frame">
    <legend>Menu</legend>
    <select id="add_role_id">
	<option value=""></option>
	<?php
	/* @var $Role \Entities\Role */
	foreach($this->Roles as $Role){
	    echo "<option value='".$Role->getId()."'>".$Role->getName()."</option>";
	}
	?>
    </select>
    <?php
    echo HTML::buttonBlue("add.png", "Add Role", "add_role", "position:relative;");
    ?>
</fieldset>
<fieldset class="padded_frame blue_frame center">
    <legend>Edit '<?php echo $this->WebAccount->getPerson()->getFullName(); ?>' Roles</legend>
    <input type="hidden" id="webaccount_id" value="<?php echo $this->WebAccount->getId();?>" />
    <ul>
    <?php
    $Roles = $this->WebAccount->getRoles();
    if(count($Roles)>0){
	/* @var $Role \Entities\Role */
	foreach($Roles as $Role){
	    echo "<li role_id='".$Role->getId()."'>".
		    HTML::buttonIcon(
			    "delete.png", 
			    "delete_role", 
			    "Remove Role", 
			    "remove_role", 
			    "padding-right:5px;"
			    ).
		    $Role->getName().
		    "</li>";
	}
    }
    else echo "<li>No roles assigned</li>";
    ?>
    </ul>
</fieldset>
<script type="text/javascript">
    WebAccount_Role = new WebAccount_Role();
    WebAccount_Role.AddRoleOnclickBind($("#add_role"));
    WebAccount_Role.RemoveRoleOnclickBind($(".remove_role"));
</script>