<?php 
use Dataservice\Html\CRUD;

echo($this->flashMessages()); 
echo CRUD\Header::factory("Rto Provider Fee Range - View")->getHtml();

$Range = $this->Range;

$crudBody = new CRUD\Body();

$crudBody->start();

$Tabs = CRUD\Tabs::factory();

$Tabs->addEntityViewTab("Information", $Range)
	->addRelationshipViewTab($Range, "RtoProvider")
	->addRelationshipViewTab($Range, "Programs")
	->addRelationshipViewTab($Range, "Values")
	->render();

$crudBody->end();

echo $Tabs->getJS();
