<?php echo($this->flashMessages()); ?>
<h1 class="header1">RTO Providers - View All</h1>
<fieldset class="padded_frame blue_frame">
    <legend>Menu</legend>
    <?php
    echo HTML::buttonBlue("add.png", "Add RTO Provider", "add_rto_provider", "position:relative;");
    ?>
</fieldset>
<fieldset class="padded_frame blue_frame">
    <legend>RTO Providers</legend>
    <?php
    /* @var $RtoProvider \Entities\RtoProvider */
    foreach($this->RtoProviders as $RtoProvider){
	echo "<div rto_provider_id='".$RtoProvider->getId()."'>";
	echo HTML::buttonIcon(
		"magnifier.png", 
		"edit_rto_provider_".$RtoProvider->getId(), 
		"Edit RTO Provider", 
		"edit_rto_provider", 
		"padding-right:5px;"
		);
	echo ":: ";
	echo $RtoProvider->getName()." - ".$RtoProvider->getDba();
    }
    ?>
</fieldset>
<script type="text/javascript">
    RtoProvider = new RtoProvider();
    RtoProvider.AddOnclickBind($("#add_rto_provider"));
    RtoProvider.EditOnclickBind($(".edit_rto_provider"));
</script>