<style>
.ui-draggable-dragging { text-shadow: 0.1em 0.1em 0.05em #4297d7 }
.add_option_right{
    width:60%;float: right;padding: 10px;
    min-height: 250px;
}
</style>
<div class="padded_frame">
<?php
$Instance   = $this->Instance;
$Product    = $Instance->getProduct();
?>
<div id="quote_product_errors" class="messenger_error ui-corner-all" style="display: none;"></div>
<div id="progress_bar" style="display: none;"></div>
<form id="configurable_instance_edit" method="post" name="configurable_instance_edit">
<div>
    <h4>Manual Edit</h4>
    <h2>
	<?php echo $Product->getName();?>
	<input type="submit" value="Save" style="float: right" />
	<input type="button" value="Cancel" style="float: right" id="form_cancel"/>
    </h2>
    <div style="color: #4297d7">* = required</div>
    <div id="quote_tabs">
	<ul>
	    <?php
	    foreach ($this->data["left"] as $array) 
	    {
		$category = $array["category"];
		?>
		<li>
		    <a id="tab_title_<?php echo $category["id"];?>" href="#<?php echo $category["index"];?>">
			<?php echo $category["name"];?>
		    </a>
		</li>
		<?php
	    }
	    ?>
	</ul>
	<?php
	foreach ($this->data["left"] as $array)
	{
	    $category	= $array["category"];
	    ?>
	    <div id="<?php echo $category["index"];?>" class="category_div">
		<div class="add_option_left" id="left_<?php echo $category["index"];?>" style="width:33%;float: left;">
		    <h1 class="header1">Drag Option &raquo;</h1>
		    <ul id="optional_list_<?php echo $category["index"];?>">
		    </ul>
		</div>
		<div id="right_<?php echo $category["index"];?>" class="border_gray add_option_right">
		    <h1 class="header1">Options &dArr;</h1>
		</div>
		<div style="clear: both;"></div>
	    </div>
	    <?php
	}
	?>
    </div>
</div>
</form>
</div>
<div style="clear: both"></div>
<script type="text/javascript">   
    var Manual = new Manual(<?php echo $Instance->getId();?>);
    
    Manual.submit(<?php echo $Instance->getId();?>, "<?php echo $this->return_url;?>");
    Manual.cancel("<?php echo $this->return_url;?>");
    Manual.addRequiredAndExistingToOptionsList(<?php echo json_encode($this->data);?>, <?php echo $Instance->getId();?>);
    Manual.OptionDeleteBind(".manual_option_delete");
</script>