<?php 
echo($this->flashMessages()); 
echo "<div>";
echo HTML::backAnchorIcon("Configurable Product Option - All", "/company/supplier-product-configurable-option/viewall");
echo "</div>";
?>
<h1 class="header1">Configurable Product Option - View</h1>
<?php
/* @var $Option \Entities\Company\Supplier\Product\Configurable\Option */
$Option	    = $this->Option;
$option_id  = $Option->getId();
$Parameters	    = $Option->getParameters();
$Configurables		    = $Option->getConfigurableProducts();
?>
<div class="blue_frame bg_blue_fade" style="margin: 20px;margin-bottom: 0px;padding: 5px;">
    <h4 class="no_space" style="color: #2000EE;">
	Info
	<?php
	echo HTML::anchorIcon(
		"pencil.png", 
		"", 
		"/company/supplier-product-configurable-option/edit/id/".$option_id,
		"margin-left:5px;"
		);
	?>
    </h4>
    <div>
	<label>Name:</label> <?php echo $Option->getName(); ?> &nbsp;&nbsp;&nbsp; 
	<label>Index:</label> <?php echo $Option->getIndex(); ?> &nbsp;&nbsp;&nbsp;
	<label>Length:</label> <?php echo $Option->getLength(); ?> &nbsp;&nbsp;&nbsp;
	<label>Code:</label> <?php echo $Option->getCode(); ?> &nbsp;&nbsp;&nbsp;
	<label>Required:</label> <?php echo $Option->isRequiredString(); ?> <br /> 
	<label>Description:</label> <span class="small"><?php echo $Option->getDescription(); ?></span>
    </div>
</div>
<div class="padded_frame" style="width: 415px;float: left;padding-top: 0px;">
    <div id="accordion">
	<h3>
	    <a href="#">Products</a>
	</h3>
	<div>
	    <ul>
	    <?php
	    /* @var $Configurable \Entities\Company\Supplier\Product\Configurable */
	    if(count($Configurables)>0){
		foreach ($Configurables as $Configurable) {
		    ?>
		    <li>
			<?php
			echo HTML::anchorIcon(
				"eye.png", 
				"", 
				"/company/supplier-product/view/id/".$Configurable->getId(),
				"margin-left:5px;"
				);
			echo $Configurable->getName();
			?>
		    </li>
		    <?php
		}
	    }
	    else echo "<li>No Configurable Products</li>";
	    ?>
	    </ul>
	</div>
	<hr />
	<h3>
	    <a href="#">Parameters</a>
	    <?php 
	    echo HTML::buttonBlue(
		    "bullet_add.png", 
		    "Add New", 
		    "option_add", 
		    "float:right;width:80px;margin-right:5px;"
		    );
	    ?>
	</h3>
	<div>
	    <ul>
	    <?php
	    /* @var $Parameter \Entities\Company\Supplier\Product\Configurable\Option\Parameter */
	    if(count($Parameters)>0){
		foreach ($Parameters as $Parameter) {
		    ?>
		    <li>
			<?php
			echo HTML::anchorIcon(
				"eye.png", 
				"", 
				"/company/supplier-product-configurable-option-parameter/view/id/".$Parameter->getId(),
				"margin-left:5px;"
				);
			echo $Parameter->getName();
			?>
		    </li>
		    <?php
		}
	    }
	    else echo "<li>No Options</li>";
	    ?>
	    </ul>
	</div>
	<hr />
    </div>
</div>
<div class="padded_frame" style="width: 415px;float: right;padding-top: 0px;">
    <h3><a href="#">Documents</a></h3>
    <div>Put Documents here</div>
</div>
<div style="clear: both;"><input type="hidden" id="option_id" value="<?php echo $option_id;?>" /></div>
<script type="text/javascript">
    Option = new Option();
    Option.ManageOptionsOnclickBind($("#options_manage"));
    Option.OptionAddOnclickBind($("#option_add"));
</script>
