<?php 
echo($this->flashMessages()); 
?>
<h1 class="header1">Configurable Product Option - View All</h1>
<fieldset class="padded_frame blue_frame">
    <legend>Menu</legend>
    <?php
    echo HTML::buttonBlue("add.png", "Add Option", "option_add", "position:relative;");
    ?>
</fieldset>
<fieldset class="padded_frame blue_frame">
    <legend>Options</legend>
    <?php
    /* @var $Option \Entities\Company\Supplier\Product\Configurable\Option */
    foreach($this->Options as $Option){
	echo "<div option_id='".$Option->getId()."'>";
	
	$Products = $Option->getConfigurableProducts();
	
	echo HTML::buttonIcon(
		"eye.png", 
		"view_option_".$Option->getId(), 
		"View Option", 
		"option_view", 
		"padding-right:5px;"
		);
	echo HTML::buttonIcon(
		"delete.png", 
		"delete_option_".$Option->getId(), 
		"Delete Option", 
		"option_delete", 
		"padding-right:5px;"
		);
	echo ":: ";
	echo $Option->getName();
	
	if(count($Products)>0)
	{
	    echo "<span class='gray small'> - ";
	    
	    $array = array();
	    
	    foreach ($Option->getConfigurableProducts() as $Configurable)
	    {
		$array[] = $Configurable->getName();
	    }
	    
	    echo implode(", ", $array);
	    echo "</span>";
	}
	else{
	    echo " - <span class='messenger_error'>No Products!</span>";
	}
    }
    ?>
</fieldset>
<script type="text/javascript">
    Option = new Option();
    Option.AddOnclickBind($("#option_add"));
    Option.ViewOnclickBind($(".option_view"));
    Option.DeleteOnclickBind($(".option_delete"));
</script>