<?php 
use Dataservice\Html\CRUD;

echo($this->flashMessages()); 
echo CRUD\Header::factory("SupplierProduct Category - View")->getHtml();

$Category = $this->Category;

$crudBody = new CRUD\Body();

$crudBody->start();

$Tabs = CRUD\Tabs::factory();

$Tabs->addEntityViewTab("Information", $Category)
	->addRelationshipViewTab($Category, "Products")
	->addRelationshipViewTab($Category, "parent")
	->addRelationshipViewTab($Category, "children")
	->addRelationshipViewTab($Category, "Images")
	->render();

$crudBody->end();

echo $Tabs->getJS();
