<?php 
use Dataservice\Html\CRUD;

echo($this->flashMessages()); 

echo CRUD\Header::factory("Rto Provider - View")->getHtml();

$RtoProvider	= $this->RtoProvider;
$Tabs		= CRUD\Tabs::factory();

CRUD\Body::factory()->start();

$Tabs->addEntityViewTab("Information", $RtoProvider)
	->addRelationshipViewTab($RtoProvider, "Company")
	->addRelationshipViewTab($RtoProvider, "Programs")
	->addRelationshipViewTab($RtoProvider, "Applications");

$Tab = CRUD\Tabs\Tab::factory("Fees");

$relationshipContent = CRUD\Content\Relationship\OneToMany::factory($RtoProvider, "Fees");

$relationshipContent->addHtmlHeaderContent($relationshipContent->relationshipPropertyName);
$relationshipContent->addHtmlHeaderContent(
	\Dataservice\Html\Anchor::addIcon(
		"Percentage", 
		"/rto-provider-fee-percentage/edit/id/0/rtoprovider_id/".$relationshipContent->parentEntity->getId(), 
		"Add Percentage Fee"
		)
	);
$relationshipContent->addHtmlHeaderContent(
	\Dataservice\Html\Anchor::addIcon(
		"Range", 
		"/rto-provider-fee-range/edit/id/0/rtoprovider_id/".$relationshipContent->parentEntity->getId(), 
		"Add Range Fee"
		)
	);
$relationshipContent->buildRelationshipBodyHtml();

$Tab->addContent($relationshipContent->getHtml());

$Tabs->addTab($Tab);

$Tabs->render();

CRUD\Body::factory()->end();

echo CRUD\Tabs::factory()->getJS();