<?php
/* @var $Location Entities\Company\Location */
$Location = $this->Location;
?>
<tr>
    <td><span style="background-color: #dad8d8;color: #FFF;">&nbsp;<?php echo $this->partialCounter;?>&nbsp;</span>&nbsp;</td>
    <td><h3><?php echo $Location->getName();?></h3></td>
    <td style="text-align: center;"><?php echo property_exists($Location, "distance") ? number_format($Location->distance)."m" : "";?></td>
    <td><?php echo $Location->getAddress()->getAddressAsString();?></td>
    <td style="text-align: center;"><?php echo $Location->getPhoneNumber()->getNumberDisplay();?></td>
</tr>