<?php 
use Dataservice\Html\CRUD;

echo($this->flashMessages()); 
echo CRUD\Header::factory("Supplier Product Simple - View")->getHtml();

$Entity = $this->Entity;

$crudBody = new CRUD\Body();

$crudBody->start();

$Tabs = CRUD\Tabs::factory();

$Tabs->addEntityViewTab("Information", $Entity)
	->addRelationshipViewTab($Entity, "Supplier")
	->addRelationshipViewTab($Entity, "Programs")
	->addRelationshipViewTab($Entity, "DeliveryTypes")
	->addRelationshipViewTab($Entity, "Categories")
	->addRelationshipViewTab($Entity, "Purposes")
	->addTab(
	    CRUD\Tabs\Tab::factory("Images")
		->addRelationshipView($Entity, "Images")
		->addContent(
		    CRUD\Content\Relationship\OneToOne::factory($Entity, "DefaultImage")
			->buildRelationshipBodyHtml()
			->addHtmlHeaderContent(
			    "Default Image ".
			    Dataservice\Html\Anchor::manageIcon(
				    "Set Default", 
				    "/supplier-product-simple/set-default-image/id/".$Entity->getId(), 
				    "Set Default"
			    )
			)
			->getHtml()
		)
	)
	->addRelationshipViewTab($Entity, "Catalogs")
	->render();

$crudBody->end();

echo $Tabs->getJS();
