<?php 
use Dataservice\Html\CRUD;

echo($this->flashMessages()); 
echo CRUD\Header::factory("Supplier Product Simple - View")->getHtml();

$Entity = $this->Entity;

$crudBody = new CRUD\Body();

$crudBody->start();

$Tabs = CRUD\Tabs::factory();

$Tabs->addEntityViewTab("Information", $Entity)
	->addRelationshipViewTab($Entity, "Supplier")
	->addRelationshipViewTab($Entity, "Programs")
	->addRelationshipViewTab($Entity, "DeliveryTypes")
	->addRelationshipViewTab($Entity, "Categories")
	->addRelationshipViewTab($Entity, "Purposes")
	->addRelationshipViewTab($Entity, "Images")
	->addRelationshipViewTab($Entity, "Catalogs")
	->render();

$crudBody->end();

echo $Tabs->getJS();
