<?php 
echo($this->flashMessages()); 
echo "<div>";
echo \Dataservice\Html\Anchor::backAnchorIcon("Company - View", "/index/view/id/".$this->Inventory->getCompany()->getId());
echo "</div>";
?>
<h1 class="header1">Inventory - View</h1>
<?php
/* @var $Inventory \Entities\Company\Inventory */
$Inventory	= $this->Inventory;
$inventory_id	= $Inventory->getId();
$Items		= $Inventory->getItems();
?>
<div class="blue_frame bg_blue_fade" style="margin: 20px;margin-bottom: 0px;padding: 5px;">
    <h4 class="no_space" style="color: #2000EE;">
	Info
    </h4>
    <div>
	Company: <?php echo $Inventory->getCompany()->getName(); ?> &nbsp;&nbsp;&nbsp;
    </div>
</div>
<div class="padded_frame" style="float: left;padding-top: 0px;">
    <div id="accordion">
	<h3>
	    <a href="#">Items</a>
	    <?php 
		echo \Dataservice\Html\Button::buttonBlue(
		    "add.png", 
		    "Add Item", 
		    "item_add", 
		    "float:right;margin-left:5px;");
		
		$select = new Dataservice_Form_Element_ProductSelect(
					    "product_select", 
					    array(
						"decorators"	=> array("ViewHelper"),
						"id"		=> "product_select",
						"style"		=> "float:right"
						)
					);
		echo $select;
	    ?>
	</h3>
	<div style="width: 800px;height:250px;overflow: auto;">
	    <table style="font-size: 10px;width:3000px;text-align: center;">
	    <?php
	    $keys = array();
	    /* @var $Item \Entities\Company\Inventory\Item\ItemAbstract */
	    if($Items->count() > 0)
	    {
		foreach ($Items as $Item)
		{
		    $display_array  = $Item->getInstance()->getDisplayArray();
		    $display_keys   = array_keys($display_array);
		    
		    if($display_keys != $keys)
			    echo "<tr><th>&nbsp</th><th>Location</th><th>".implode ("</th><th>", $display_keys)."</th></tr>";
		    
		    $keys = $display_keys;
		    
		    $button = \Dataservice\Html\Anchor::anchorIcon(
				"bullet_go.png", 
				"", 
				"/inventory-item/view/id/".$Item->getId(),
				"margin-left:5px;"
				);
		    echo "<tr><td>$button</td><td>".($Item->getLocation() ? $Item->getLocation()->getName() : "-")."</td><td>".implode ("</td><td>", $display_array)."</td></tr>";
		}
	    }
	    else echo "No Items"; 
	    ?>
	    </table>
	</div>
    </div>
</div>
<div style="clear: both;"><input type="hidden" id="inventory_id" value="<?php echo $inventory_id;?>" /></div>
<script type="text/javascript">
    Company_Inventory = new Company_Inventory();
    Company_Inventory.AddItemOnclickBind($("#item_add"));
</script>
