<?php 
use Dataservice\Html\CRUD;

echo($this->flashMessages()); 

echo CRUD\Header::factory("Company Inventory - View")->getHtml();

$Inventory = $this->Inventory;

CRUD\Body::factory()->start();
CRUD\Tabs::factory()
	->addEntityViewTab("Information", $Inventory)
	->addRelationshipViewTab($Inventory, "Items")
	->render();

CRUD\Body::factory()->end();

echo CRUD\Tabs::factory()->getJS();
