<?php
$links = array(
    "Home"		=> "/index",
    "Products"		=> "/products",
    "Gallery"		=> "/index/gallery",
    "Build Your Own"	=> "/products/builder",
    "Quality Control"   => "/index/qualitycontrol",
    "Financing"		=> "/index/financing",
    "Where to buy"	=> "/locations",
    "Why Texwin"	=> "/index/whytexwin",
    "Who are we"	=> "/index/aboutus",
    "Contact Us"	=> "/contactus",
    "Become a dealer"	=> "/beadealer"
);
?>
<div id="main_sidebar">
    <?php
    foreach ($links as $text => $url){
	?>
	<div id="sidebar_links">
	    <a href="<?php echo $url;?>" class="sidebar_link">
		<?php echo strtoupper($text);?>
	    </a>
	</div>
	<?php
    }
    ?>
</div>
<div style="margin-left:90px;margin-top: 20px;">
    <!-- AddThis Button BEGIN -->
    <div class="addthis_toolbox addthis_default_style ">
    <a class="addthis_button_preferred_1"></a>
    <a class="addthis_button_preferred_2"></a>
    <a class="addthis_button_preferred_3"></a>
    <a class="addthis_button_preferred_4"></a>
    <a class="addthis_button_compact"></a>
    </div>
    <script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=ra-4ddc3f182dffe194"></script>
    <!-- AddThis Button END -->
</div>
<div style="text-align: left;padding-left:50px;padding-top: 15px;">
    <!-- LiveZilla Chat Button Link Code (ALWAYS PLACE IN BODY ELEMENT) --><a href="javascript:void(window.open('http://texwincarports.com/livezilla/chat.php','','width=590,height=610,left=0,top=0,resizable=yes,menubar=no,location=no,status=yes,scrollbars=yes'))"><img src="http://texwincarports.com/livezilla/image.php?id=01&amp;type=inlay" width="120" height="30" border="0" alt="LiveZilla Live Help"></a><!-- http://www.LiveZilla.net Chat Button Link Code --><!-- LiveZilla Tracking Code (ALWAYS PLACE IN BODY ELEMENT) --><div id="livezilla_tracking" style="display:none"></div><script type="text/javascript">
var script = document.createElement("script");script.type="text/javascript";var src = "http://texwincarports.com/livezilla/server.php?request=track&output=jcrpt&nse="+Math.random();setTimeout("script.src=src;document.getElementById('livezilla_tracking').appendChild(script)",1);</script><noscript><img src="http://texwincarports.com/livezilla/server.php?request=track&amp;output=nojcrpt" width="0" height="0" style="visibility:hidden;" alt=""></noscript><!-- http://www.LiveZilla.net Tracking Code -->
</div>
<div style="text-align: justify;color: gray;font-size: 13px;padding:30px;padding-right: 10px;padding-top: 15px;">
    <h1 style="font-size: 12pt;">Welcome to the home of <b>Texwin carports and metal buildings</b>.</h1>
Texas is a wonderful place to live but with scorching sun, rain, hail, hurricanes, tornadoes or other severe weather factors, protecting your valuable Autos, Boats and other equipment is essential. 	We have the perfect solution – in both size and function – for storing and protecting your valuables. So if you need more space for your business, shade for livestock, covered parking for RV’s, Tractors, Cars or even a patio cover we appreciate the chance to bid your project.

</div>