<?php 
echo($this->flashMessages()); 
echo "<div>";
echo HTML::backAnchorIcon("Customer Search", "/customer/search");
echo "</div>";
$customer	= $this->Customer;
$customer_id	= $customer->getId();
$addresses	= $customer->getPersonAddresses();
$phones		= $customer->getPhoneNumbers();
$emails		= $customer->getEmailAddresses();
$contacts	= $customer->getContacts();
?>
<div class="blue_frame bg_blue_fade" style="margin: 20px;margin-bottom: 0px;padding: 5px;">
    <h3 class="no_space" style="color: #2000EE;">Customer Info</h4>
    <div>Name:<?php echo $customer->getFullName(); ?> &nbsp;&nbsp;&nbsp; Company:<?php echo $customer->getCompany(); ?></div>
</div>
<div class="padded_frame" style="width: 415px;float: left;padding-top: 0px;">
    <div id="accordion">
	<h3>
	    <a href="#">Address</a>
	    <?php echo HTML::buttonBlue("building_add.png", "Add Address", "address_add", "float:right;width:110px;");?>
	</h3>
	<div>
	    <?php
	    /* @var $Address \Entities\Address */
	    foreach ($addresses as $Address) {
		?>
		<h4 class="no_space bg_blue_fade blue_frame" style="padding: 3px;margin-bottom: 3px;">
		    <?php 
		    echo $Address->getName();
		    echo HTML::anchorIcon(
			    "pencil.png", 
			    "", 
			    "/customer/editaddress/customer_id/".$customer_id."/address_id/".$Address->getId(),
			    "margin-left:5px;"
			    );
		    ?>
		</h4>
		<label for="addr_1_addr1">Address 1:</label>
		<div id="addr_1_addr1" style="display: inline;"><?php echo $Address->getAddress1(); ?></div><br />
		<label for="addr_1_addr2">Address 2:</label>
		<div id="addr_1_addr2" style="display: inline;"><?php echo $Address->getAddress2(); ?></div><br />
		<label for="addr_1_csz">City/ST/Zip:</label>
		<div id="addr_1_csz" style="display: inline;">
		    <?php 
		    echo $Address->getCity().", ".
			    $Address->getState()." ".
			    $Address->getZip1()."-".
			    $Address->getZip2(); ?>
		</div>
		<?php
	    }
	    ?>
	</div>
	<hr />
	<h3>
	    <a href="#">Phone</a>
	    <?php 
	    echo HTML::buttonBlue(
		    "phone_add.png", 
		    "Add Phone", 
		    "phone_add", "float:right;width:110px;"
		    );?>
	</h3>
	<div>
	    <?php
	    /* @var $Phonenumber \Entities\Phonenumber */
	    foreach ($phones as $Phonenumber) {
		?>
		<h4 class="no_space bg_blue_fade blue_frame" style="padding: 3px;margin-bottom: 3px;">
		    <?php 
		    echo $Phonenumber->getType(); 
		    echo HTML::anchorIcon(
			    "pencil.png", 
			    "", 
			    "/customer/editphone/customer_id/".$customer_id."/phonenumber_id/".
				$Phonenumber->getId(), 
			    "margin-left:5px;"
			    );
		    ?>
		</h4>
		<label for="phone1">Num:</label>
		<div id="phone1" style="display: inline;">
		    <?php 
		    echo "(".$Phonenumber->getAreaCode().") ".$Phonenumber->getNum1()."-".$Phonenumber->getNum2(); 
		    ?>
		</div><br />
		<label for="ext1">Ext:</label>
		<div id="ext1" style="display: inline;">
		    <?php 
		    echo $Phonenumber->getExtension(); 
		    ?>
		</div>
		<?php
	    }
	    ?>
	</div>
	<hr />
	<h3>
	    <a href="#">Email</a>
	    <?php 
	    echo HTML::buttonBlue(
		    "email_add.png", 
		    "Add Email", 
		    "email_add", "float:right;width:110px;"
		    );?>
	</h3>
	<div>
	    <?php
	    /* @var $Emailaddress \Entities\Emailaddress */
	    foreach ($emails as $Emailaddress) {
		?>
		<h4 class="no_space bg_blue_fade blue_frame" style="padding: 3px;margin-bottom: 3px;">
		    <?php 
		    echo $Emailaddress->getType(); 
		    echo HTML::anchorIcon(
			    "pencil.png", 
			    "", 
			    "/customer/editemail/customer_id/".$customer_id."/emailaddress_id/".
				$Emailaddress->getId(), 
			    "margin-left:5px;"
			    );
		    ?>
		</h4>
		<label for="emailaddress">Address:</label>
		<div id="emailaddress" style="display: inline;">
		    <?php 
		    echo $Emailaddress->getAddress(); 
		    ?>
		</div>
		<?php
	    }
	    ?>
	</div>
    </div>
</div>
<div class="padded_frame" style="width: 415px;float: right;padding-top: 0px;">
    <h3>
	<a href="#">Contacts</a>
	<span style="float: right;">
	    <select id="contact_type_id_select">
		<option class="gray small" value="">Choose contact medium</option>
		<?php 
		foreach($this->Locations as $Location){
		    echo "<option type_string='location' value='".$Location->getId()."'>Walk In: ".$Location->getName()."</option>";
		}
		foreach($phones as $Phonenumber){
		    echo "<option type_string='phone' value='".$Phonenumber->getId()."'>Phone: ".$Phonenumber->getNumberDisplay()."</option>";
		}
		foreach($emails as $Emailaddress){
		    echo "<option type_string='email' value='".$Emailaddress->getId()."'>Email: ".$Emailaddress->getAddress()."</option>";
		}
		?>
	    </select>
	    <?php 
	    echo HTML::buttonBlue(
		    "phone_sound.png", 
		    "Add Contact", 
		    "contact_add", 
		    "contact_add", 
		    "padding-left:3px;"
		    );?>
	</span>
    </h3>
    <div>
	<div class="" style="max-height: 300px;overflow: auto;">
	    <?php
	    /* @var $Contact \Entities\Contact */
	    foreach ($contacts as $Contact) {
		?>
		<h4 class="no_space bg_blue_fade blue_frame" style="margin-bottom: 3px;padding:3px;">
		    <?php 
		    echo $Contact->getCreated()->format("m-d-Y, g:i a")." - ".$Contact->getPerson()->getFirstName(); 
		    echo HTML::anchorIcon(
			    "pencil.png", 
			    "", 
			    "/customer/editcontact/customer_id/".$customer_id."/contact_id/".
				$Contact->getId(), 
			    "margin-left:5px;"
			    );
		    ?>
		</h4>
		<label for="contact_type">Type:</label>
		<div id="contact_type" style="display: inline;">
		    <?php 
		    echo $Contact->getType()."-".$Contact->getTypeDetail(); 
		    ?>
		</div><br />
		<label for="contact_note">Note:</label>
		<div id="contact_note" style="display: inline;">
		    <?php 
		    echo HTML::truncateString($Contact->getNote(), 40);
		    ?>
		</div><br />
		<label for="contact_result">Result:</label>
		<div id="contact_result" style="display: inline;">
		    <?php 
		    echo $Contact->getResultDisplay();
		    ?>
		</div><br /><br />
		<?php
	    }
	    ?>
	</div>
    </div>
    <hr />
    <h3><a href="#">Orders</a></h3>
    <div>Put Orders here</div>
    <hr />
    <h3><a href="#">Documents</a></h3>
    <div>Put Documents here</div>
</div>
<div style="clear: both;"><input type="hidden" id="customer_id" value="<?php echo $customer_id;?>" /></div>
<script type="text/javascript">
    Customer = new Customer();
    Customer.AddPhoneClickBind("phone_add");
    Customer.AddAddressClickBind("address_add");
    Customer.AddEmailClickBind("email_add");
    Customer.AddContactClickBind("contact_add");
</script>
