<!DOCTYPE>
<html>
<head>
    <?php 
    echo $this->headTitle();
    $this->headLink()->prependStylesheet('/css/global.css');
    echo $this->headLink();
    
    echo $this->headMeta();
    $this->headScript()->prependFile('/javascript/common.js');
    $this->headScript()->prependFile('/javascript/jquery/jquery.js');
    
    echo $this->headScript();
    ?>
</head>
<body>
	<?php
	echo $this->layout()->content;
	?>
</body>
</html>
