<!DOCTYPE>
<html>
<head>
    <?php 
    echo $this->headTitle();
    
    $this->headLink()->prependStylesheet('/css/layout.css');
    $this->headLink()->prependStylesheet('/css/global.css');
    #--Superfish Menu
    $this->headLink()->appendStylesheet(BASE_URL.'/css/superfish.css');
    echo $this->headLink();
    
    echo $this->headMeta();
    $this->headScript()->prependFile('/javascript/common.js');
    $this->headScript()->prependFile('/javascript/jquery.js');
    $this->headScript()->appendFile('/javascript/layout.js');
    
    #--Superfish Menu
    $this->headScript()->appendFile(BASE_URL.'/javascript/hoverIntent.js');
    $this->headScript()->appendFile(BASE_URL.'/javascript/superfish.js');
    
    echo $this->headScript();
    ?>
    <script language="JavaScript" type="text/javascript">
	l = new layout;
	l.nav_menu($("ul.sf-menu"));
    </script>
</head>
<body>
    <div class="main_outer">
	<div class="main_header">
	    <div class="logo_cont">
		<span class="logo">Winslows Inc.</span> - Dashboard
	    </div>
	    <div style="float: right;padding: 8px;color: #FFF;"><?php echo $this->profilelink();?></div>
	</div>
	<?php
	#--Get Auth Instance
        $auth = Zend_Auth::getInstance();

	#--Check if user logged in
        if (!$auth->hasIdentity()){
	    if($_SERVER["REQUEST_URI"] != "/login/index")
	    header('Location: /login/index');
	}
	else
	{
	    ?>
	    <div id="nav_container">
		<?php
		$menu_array = array(
		    "home"  => array(
			"label"	=> "Home",
			"url"	=> "/index",
			"icon"	=> "house.png"
		    ),
		    "sales"  => array(
			"label"	=> "Sales",
			"icon"	=> "money.png",
			"subs"	=> array(
			    "inventory" => array(
				"label"	=> "Inventory",
				"url"	=> "/inventory",
//				"subs"	=> array(
//				    "test" => array(
//					"label"	=> "Test",
//					"url"	=> "/test"
//				    )
//				)
			    ),
			    "products" => array(
				"label"	=> "Products",
				"url"	=> "/products",
			    )
			)
		    ),
		    "users"  => array(
			"label"	=> "Users",
			"url"	=> "/users/",
			"icon"	=> "user.png"
		    ),
		    "maintenance"  => array(
			"label"	=> "Maint.",
			"icon"	=> "page_gear.png",
			"subs"	=> array(
			    "privileges" => array(
				"label"	=> "Groups/Privileges",
				"url"	=> "/maintenance/groupsview"
			    ),
			    "code_builder" => array(
				"label"	=> "Codebuilder",
				"url"	=> "/codebuilder/optionsview"
			    )
			)
		    ),
		);
		HTML::superFish_menu($menu_array);
		?>
		<div id="nav_filler"></div>
	    </div>
	    <?php 
	}
	echo $this->layout()->content 
	?>
	<div style="height: 5px;"></div>
    </div>
</body>
</html>
