<?php 
use Dataservice\Html\CRUD;

echo($this->flashMessages()); 

echo CRUD\Header::factory("Employee Account - View")->getHtml();

$Account    = $this->Account;
$Tabs	    = CRUD\Tabs::factory();

CRUD\Body::factory()->start();

$Tab = CRUD\Tabs\Tab::factory("Information");

$EntityView = CRUD\EntityView::factory($Account);

$EntityView->buildBody()
	    ->addHeaderHtml($Account->getClassName())
	    ->addHeaderHtml(
		Dataservice\Html\Anchor::anchorIcon(
		    "lock.png", 
		    "Change Password", 
		    "/employee-account/change-password/id/".$Account->getId(), 
		    "", 
		    "Change Account Password"
		)
	    );

$Tab->addContent($EntityView->getHtml());

$Tabs->addTab($Tab)
	->addRelationshipViewTab($Account, "Employee")
	->addRelationshipViewTab($Account, "Website")
	->addRelationshipViewTab($Account, "Roles")
	->render();

CRUD\Body::factory()->end();

echo CRUD\Tabs::factory()->getJS();