<?php 
use Dataservice\Html\CRUD;

echo($this->flashMessages()); 

echo CRUD\Header::factory("Employee Account - View")->getHtml();

$Account = $this->Account;

CRUD\Body::factory()->start();

CRUD\Tabs::factory()
	->addEntityViewTab("Information", $Account)
	->addRelationshipViewTab($Account, "Employee")
	->addRelationshipViewTab($Account, "Website")
	->addRelationshipViewTab($Account, "Roles")
	->render();

CRUD\Body::factory()->end();

echo CRUD\Tabs::factory()->getJS();