<?php echo($this->flashMessages()); ?>
<fieldset class="padded_frame blue_frame">
    <legend>Menu</legend>
    <?php
    echo HTML::buttonBlue("add.png", "Add Employee", "add_employee", "position:relative;");
    ?>
</fieldset>
<fieldset class="padded_frame blue_frame">
    <legend>Employees</legend>
    <?php
    /* @var $Employee \Entities\Employee */
    foreach($this->Employees as $Employee){
	echo "<div employee_id='".$Employee->getId()."'>";
	echo HTML::buttonIcon(
		"user_edit.png", 
		"editemployee_".$Employee->getId(), 
		"Edit Employee", 
		"edit_employee", 
		"padding-right:5px;"
		);
	echo ":: ";
	echo $Employee->getFullName();
    }
    ?>
</fieldset>
<script type="text/javascript">
    Hr_Employee = new Hr_Employee();
    Hr_Employee.AddOnclickBind($("#add_employee"));
    Hr_Employee.EditOnclickBind($(".edit_employee"));
</script>