<div style="margin: 35px;margin-top: 0px;">
    <h2 style="color: #0092ef;">
	Become A Texwin Carports Dealer
    </h2>
    <hr></hr>
    <div style="padding:30px;">
	<div style="float: left;">
	    <span style="color: #0092ef;font-weight: 600;">How Do I Become A Dealer?</span>
	    <img src="<?php echo BASE_URL;?>/img/texwin/handshake.jpg" style="float: left;width:120px;vertical-align: top;margin-right: 15px;"/>
	    <p>Are you an established retail company that cares about your customers and wants to be 
	    able to offer them a quality product? We are a family oriented manufacturer that stands out above the rest. 
	    We would like to add you to our family of retailers. Please fill out the form below or contact us at (800) 636-4700.</p>
	</div>
	<div style="clear: both;"></div>
	<div>
	    <?php echo $this->form;?>
	</div>
    </div>
</div>