<?php

namespace Proxies\__CG__\Entities\Company\RtoProvider;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Program extends \Entities\Company\RtoProvider\Program implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getRtoProvider()
    {
        $this->__load();
        return parent::getRtoProvider();
    }

    public function setRtoProvider(\Entities\Company\RtoProvider $RtoProvider)
    {
        $this->__load();
        return parent::setRtoProvider($RtoProvider);
    }

    public function getRtoSaleType()
    {
        $this->__load();
        return parent::getRtoSaleType();
    }

    public function setRtoSaleType(\Entities\Company\Lead\Quote\Item\SaleType\Rto $RtoSaleType)
    {
        $this->__load();
        return parent::setRtoSaleType($RtoSaleType);
    }

    public function getProducts()
    {
        $this->__load();
        return parent::getProducts();
    }

    public function addProduct(\Entities\Company\Supplier\Product\ProductAbstract $Product)
    {
        $this->__load();
        return parent::addProduct($Product);
    }

    public function removeProduct(\Entities\Company\Supplier\Product\ProductAbstract $Product)
    {
        $this->__load();
        return parent::removeProduct($Product);
    }

    public function getFees()
    {
        $this->__load();
        return parent::getFees();
    }

    public function addFee(\Entities\Company\RtoProvider\Fee\FeeAbstract $Fee)
    {
        $this->__load();
        return parent::addFee($Fee);
    }

    public function removeFee(\Entities\Company\RtoProvider\Fee\FeeAbstract $Fee)
    {
        $this->__load();
        return parent::removeFee($Fee);
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function getName()
    {
        $this->__load();
        return parent::getName();
    }

    public function setName($name)
    {
        $this->__load();
        return parent::setName($name);
    }

    public function getPaymentCount()
    {
        $this->__load();
        return parent::getPaymentCount();
    }

    public function setPaymentCount($payment_count)
    {
        $this->__load();
        return parent::setPaymentCount($payment_count);
    }

    public function getFactor()
    {
        $this->__load();
        return parent::getFactor();
    }

    public function setFactor($factor)
    {
        $this->__load();
        return parent::setFactor($factor);
    }

    public function getNameIndex()
    {
        $this->__load();
        return parent::getNameIndex();
    }

    public function setNameIndex($name_index)
    {
        $this->__load();
        return parent::setNameIndex($name_index);
    }

    public function updated()
    {
        $this->__load();
        return parent::updated();
    }

    public function getCreated()
    {
        $this->__load();
        return parent::getCreated();
    }

    public function setCreated(\DateTime $created)
    {
        $this->__load();
        return parent::setCreated($created);
    }

    public function getUpdated()
    {
        $this->__load();
        return parent::getUpdated();
    }

    public function populate(array $array)
    {
        $this->__load();
        return parent::populate($array);
    }

    public function filterCollectionByfield(\Doctrine\Common\Collections\ArrayCollection $ArrayCollection, $field, $value)
    {
        $this->__load();
        return parent::filterCollectionByfield($ArrayCollection, $field, $value);
    }

    public function toArray()
    {
        $this->__load();
        return parent::toArray();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'name', 'name_index', 'payment_count', 'factor', 'created', 'updated', 'RtoProvider', 'Products', 'Fees', 'RtoSaleType');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}