<?php

namespace Proxies\__CG__\Entities\Company\Lead\Quote\Item\SaleType;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Rto extends \Entities\Company\Lead\Quote\Item\SaleType\Rto implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setProgram(\Entities\Company\RtoProvider\Program $Program)
    {
        $this->__load();
        return parent::setProgram($Program);
    }

    public function getProgram()
    {
        $this->__load();
        return parent::getProgram();
    }

    public function getDescriminator()
    {
        $this->__load();
        return parent::getDescriminator();
    }

    public function isProductAllowed(\Entities\Company\Supplier\Product\ProductAbstract $Product)
    {
        $this->__load();
        return parent::isProductAllowed($Product);
    }

    public function getName()
    {
        $this->__load();
        return parent::getName();
    }

    public function isApproved()
    {
        $this->__load();
        return parent::isApproved();
    }

    public function getPaymentsTotalAmountPrice(\Dataservice_Price $Price)
    {
        $this->__load();
        return parent::getPaymentsTotalAmountPrice($Price);
    }

    public function getFeesPrice(\Dataservice_Price $Price)
    {
        $this->__load();
        return parent::getFeesPrice($Price);
    }

    public function getDownPaymentPrice(\Dataservice_Price $Price)
    {
        $this->__load();
        return parent::getDownPaymentPrice($Price);
    }

    public function getPaymentsCount()
    {
        $this->__load();
        return parent::getPaymentsCount();
    }

    public function getPaymentsAmountPrice(\Dataservice_Price $Price)
    {
        $this->__load();
        return parent::getPaymentsAmountPrice($Price);
    }

    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function addItem(\Entities\Company\Lead\Quote\Item $Item)
    {
        $this->__load();
        return parent::addItem($Item);
    }

    public function getItems()
    {
        $this->__load();
        return parent::getItems();
    }

    public function updated()
    {
        $this->__load();
        return parent::updated();
    }

    public function getCreated()
    {
        $this->__load();
        return parent::getCreated();
    }

    public function setCreated(\DateTime $created)
    {
        $this->__load();
        return parent::setCreated($created);
    }

    public function getUpdated()
    {
        $this->__load();
        return parent::getUpdated();
    }

    public function populate(array $array)
    {
        $this->__load();
        return parent::populate($array);
    }

    public function toArray()
    {
        $this->__load();
        return parent::toArray();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'created', 'updated', 'Items', 'Program');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}