<?php

namespace Proxies\__CG__\Entities;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Supplier extends \Entities\Supplier implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function addCompany(\Entities\Company $Company)
    {
        $this->__load();
        return parent::addCompany($Company);
    }

    public function removeCompany(\Entities\Company $Company)
    {
        $this->__load();
        return parent::removeCompany($Company);
    }

    public function getCompanies()
    {
        $this->__load();
        return parent::getCompanies();
    }

    public function addSupplierAddress(\Entities\SupplierAddress $SupplierAddress)
    {
        $this->__load();
        return parent::addSupplierAddress($SupplierAddress);
    }

    public function getSupplierAddresses()
    {
        $this->__load();
        return parent::getSupplierAddresses();
    }

    public function addProduct(\Entities\Product $Product)
    {
        $this->__load();
        return parent::addProduct($Product);
    }

    public function getProducts()
    {
        $this->__load();
        return parent::getProducts();
    }

    public function updated()
    {
        $this->__load();
        return parent::updated();
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function getName()
    {
        $this->__load();
        return parent::getName();
    }

    public function setName($name)
    {
        $this->__load();
        return parent::setName($name);
    }

    public function getCreated()
    {
        $this->__load();
        return parent::getCreated();
    }

    public function setCreated($created)
    {
        $this->__load();
        return parent::setCreated($created);
    }

    public function getUpdated()
    {
        $this->__load();
        return parent::getUpdated();
    }

    public function populate(array $array)
    {
        $this->__load();
        return parent::populate($array);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'name', 'created', 'updated', 'Companies', 'SupplierAddresses', 'Products');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}