<?php

namespace Proxies\__CG__\Entities\Company\Lead;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Quote extends \Entities\Company\Lead\Quote implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function addItem(\Entities\Company\Lead\Quote\Item $Item)
    {
        $this->__load();
        return parent::addItem($Item);
    }

    public function getItems()
    {
        $this->__load();
        return parent::getItems();
    }

    public function setLead(\Entities\Company\Lead $Lead)
    {
        $this->__load();
        return parent::setLead($Lead);
    }

    public function getLead()
    {
        $this->__load();
        return parent::getLead();
    }

    public function getDueAtSaleTotalPrice()
    {
        $this->__load();
        return parent::getDueAtSaleTotalPrice();
    }

    public function getTotal()
    {
        $this->__load();
        return parent::getTotal();
    }

    public function getTotalSafe()
    {
        $this->__load();
        return parent::getTotalSafe();
    }

    public function getTotalItemsQuantity()
    {
        $this->__load();
        return parent::getTotalItemsQuantity();
    }

    public function removeItem(\Entities\Company\Lead\Quote\Item $Item)
    {
        $this->__load();
        return parent::removeItem($Item);
    }

    public function isValid()
    {
        $this->__load();
        return parent::isValid();
    }

    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function updated()
    {
        $this->__load();
        return parent::updated();
    }

    public function getCreated()
    {
        $this->__load();
        return parent::getCreated();
    }

    public function setCreated(\DateTime $created)
    {
        $this->__load();
        return parent::setCreated($created);
    }

    public function getUpdated()
    {
        $this->__load();
        return parent::getUpdated();
    }

    public function populate(array $array)
    {
        $this->__load();
        return parent::populate($array);
    }

    public function toArray()
    {
        $this->__load();
        return parent::toArray();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'total', 'created', 'updated', 'Lead', 'Items');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}