<?php 
use Dataservice\Html\CRUD;

echo($this->flashMessages()); 
echo CRUD\Nav::factory("Company", "/index/view/id/".$this->Location->getCompany()->getId())->getHtml();
echo CRUD\Header::factory("Location - View")->getHtml();

/* @var $Location \Entities\Company\Location */
$Location = $this->Location;

$crudBody = new CRUD\Body();

$crudBody->start();

$Tabs = CRUD\Tabs::factory();

$Tabs->addEntityViewTab("Information", $Location)
	->addTab(
		CRUD\Tabs\Tab::factory("Contact Info")
		    ->addRelationshipView($Location, "Address")
		    ->addRelationshipView($Location, "PhoneNumber")
	)
	->addRelationshipViewTab($Location, "Employees")
	->render();
//$Tabs->addEntityViewTab("Information", $Location)
//    ->addTab(
//	CRUD\Tabs\Tab::factory(("Contact Info"))
//	    ->addRelationshipContent(CRUD\Content\Relationship\OneToOne::factory($Location, "Address")
//	    ->addRelationshipContent(CRUD\EntityView::factory($Location->getPhoneNumber()))
//    )
//    ->addCollectionListTab("Employees", $Location, "Employees")
//    ->render();

$crudBody->end();

echo $Tabs->getJS();
