<?php 
use Dataservice\Html\CRUD;

echo($this->flashMessages()); 
echo CRUD\Header::factory("Location - View")->getHtml();

/* @var $Location \Entities\Company\Location */
$Location = $this->Location;

$crudBody = new CRUD\Body();

$crudBody->start();

$Tabs = CRUD\Tabs::factory();

$Tabs->addEntityViewTab("Information", $Location)
	->addRelationshipViewTab($Location, "Company")
	->addTab(
		CRUD\Tabs\Tab::factory("Contact Info")
		    ->addRelationshipView($Location, "Address")
		    ->addRelationshipView($Location, "PhoneNumber")
	)
	->addRelationshipViewTab($Location, "Employees")
	->addRelationshipViewTab($Location, "InventoryItems")
	->render();

$crudBody->end();

echo $Tabs->getJS();
