<?php 
echo($this->flashMessages()); 
echo "<div>";
echo HTML::backAnchorIcon("Inventory - View", "/inventory/view/id/".$this->Item->getInventory()->getId());
echo "</div>";
?>
<h1 class="header1">Item Item - View</h1>
<?php
/* @var $Item \Entities\Company\Inventory\Item */
$Item		= $this->Item;
$item_id	= $Item->getId();
$Instance	= $Item->getInstance();
$Product	= $Instance->getProduct();
?>
<div class="blue_frame bg_blue_fade" style="margin: 20px;margin-bottom: 0px;padding: 5px;">
    <h4 class="no_space" style="color: #2000EE;">
	Info
	<?php
	echo HTML::anchorIcon(
		"pencil.png", 
		"", 
		"/inventory-item/edit/id/".$Item->getId(),
		"margin-left:5px;"
		);
	?>
    </h4>
    <div>
	Quantity: <?php echo $Item->getQuantity(); ?> &nbsp;&nbsp;&nbsp;
	Location: <?php echo $Item->getLocation() ? $Item->getLocation()->getName() : "*Not Set*" ?> &nbsp;&nbsp;&nbsp;
    </div>
</div>
<div class="padded_frame" style="width: 415px;float: left;padding-top: 0px;">
    <div id="accordion">
	<h3>
	    <a href="#">Product</a>
	    <?php
	    if($Product->getDescriminator() == "Configurable")
	    {
		echo HTML::buttonBlue(
			"pencil.png", 
			"Builder", 
			"product_builder", 
			"float:right;width:80px;margin-left:5px;"
			);
		echo HTML::buttonBlue(
			"pencil.png", 
			"Manual", 
			"product_manual", 
			"float:right;width:80px;margin-left:5px;"
			);
	    }
	    ?>
	</h3>
	<div>
	    <?php
	    /* @var $InstancePrice Dataservice_Price */
	    $InstancePrice = $Instance->getPriceSafe();
	    ?>
	    <h4 class="no_space bg_blue_fade blue_frame" style="padding: 3px;margin-bottom: 3px;">
		<?php 
		echo $Instance->getProduct()->getName();
		?>
	    </h4>
	    <label>Price Each:</label>
	    <div style="display: inline;"><?php echo $InstancePrice->getDisplayPrice(); ?></div>
	    <br />
	    <br />
	    <?php
	    if($Product->getDescriminator() == "Configurable")
	    {
		?>
		<label>Price Details:</label>
		<div style="display: inline;">
		    <?php echo $InstancePrice->getDisplayDetails();?>
		</div>
		<br />
		<label>Options:</label>
		<div style="display: inline;">
		    <?php echo $Instance->getOptionsDisplay();?>
		</div>
		<?php
	    }
	    ?>
	</div>
	<hr />
    </div>
</div>
<div class="padded_frame" style="width: 415px;float: right;padding-top: 0px;">
    <h3><a href="#">Documents</a></h3>
    <div>Put Documents here</div>
</div>
<div style="clear: both;"><input type="hidden" id="item_id" value="<?php echo $item_id;?>" /></div>
<script type="text/javascript">
    Company_Inventory_Item = new Company_Inventory_Item;
    Company_Inventory_Item.ProductBuilderOnclickBind($("#product_builder"), "<?php echo $Instance->getId();?>");
    Company_Inventory_Item.ProductManualOnclickBind($("#product_manual"), "<?php echo $Instance->getId();?>");
</script>
