<?php

namespace Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * Employee
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Employee extends EntityRepository
{  
}