<?php

namespace Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * Person
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Location extends EntityRepository
{  
    
}