<?php

namespace Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * PersonAddress
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonPhoneNumber extends EntityRepository
{  
}