<?php

namespace Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * Person
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Person extends EntityRepository
{  
    public function findNewestPeople() {
   
      $now	 = new \DateTime("now");
      $oneDayAgo = $now->sub(new \DateInterval('P1D'))
                       ->format('Y-m-d h:i:s');
      $qb = $this->_em->createQueryBuilder();
      $qb->select('p.first_name, p.middle_name, p.last_name, p.suffix')
          ->from('Entities\Person', 'p')
          ->where('p.created >= :date')
          ->setParameter('date', $oneDayAgo);
   
      return $qb->getQuery()->getResult();
  }  
}