<?php

namespace Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * WebAccount
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Privilege extends EntityRepository
{  
}