<?php

namespace Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * QuoteProduct
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuoteProduct extends EntityRepository
{  
}