<?php

namespace Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * QuoteProductOptionValue
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuoteProductOptionValue extends EntityRepository
{  
}