<?php

namespace Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * Quote
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Quote extends EntityRepository
{  
}