<?php

namespace Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * Webaccount
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Webaccount extends EntityRepository
{  
}