<?php 
use Dataservice\Html\CRUD;

echo($this->flashMessages()); 

echo CRUD\Header::factory("Website - View")->getHtml();

$Website = $this->Website;

CRUD\Body::factory()->start();

$Tabs = CRUD\Tabs::factory();

$Tabs->addEntityViewTab("Information", $Website)
    ->addRelationshipViewTab($Website, "Company")
    ->addRelationshipViewTab($Website, "Menus");

$Tab = CRUD\Tabs\Tab::factory("Resources");

$relationshipContent = CRUD\Content\Relationship\OneToMany::factory($Website, "Resources");

$relationshipContent->addHtmlHeaderContent($relationshipContent->relationshipClassName);
$relationshipContent->addHtmlHeaderContent(
	\Dataservice\Html\Anchor::manageIcon(
		"", 
		"/website/build-resources/id/".$relationshipContent->parentEntity->getId(), 
		"Build Resources"
		)
	);
$relationshipContent->addHtmlHeaderContent(
	\Dataservice\Html\Anchor::trashIcon(
		"", 
		"/website/build-resources/id/".$relationshipContent->parentEntity->getId(), 
		true,
		"Build Resources"
		)
	);
$relationshipContent->buildRelationshipBodyHtml();

$Tab->addContent($relationshipContent->getHtml());

$Tabs->addTab($Tab);

$Tabs->addRelationshipViewTab($Website, "Roles")
    ->render();

CRUD\Body::factory()->end();

echo CRUD\Tabs::factory()->getJS();