<?php 
use Dataservice\Html\CRUD;

echo($this->flashMessages()); 

echo CRUD\Header::factory("Lead Email Address - View")->getHtml();

$EmailAddress = $this->EmailAddress;

CRUD\Body::factory()->start();

CRUD\Tabs::factory()
	->addEntityViewTab("Information", $EmailAddress)
	->addRelationshipViewTab($EmailAddress, "Lead")
	->addRelationshipViewTab($EmailAddress, "Contacts")
	->render();

CRUD\Body::factory()->end();

echo CRUD\Tabs::factory()->getJS();