<div id="gallery-main-container">
    <div id="gallery-header-container-left">
        <div id="gallery-header-content-left">
            <h1>Browse By</h1>
        </div>
    </div>
    <div id="gallery-header-container-right">
        <div id="gallery-header-content-right">
            <h1>Gallery</h1>
        </div>
    </div>
    <div id="gallery-left-navigation">
        <ul>
                <h3>Building Type</h3>
                    <li>Carport</li>
                    <li>Doghouse</li>
                    <li>Garage</li>
                    <li>Storage Shed</li>
                <h3>Use</h3>
                    <li>Auto/Boat/RV</li>
                    <li>Pets</li>
                    <li>Storage</li>
                <h3>Building Material</h3>
                    <li>Metal</li>
                    <li>Wood</li>
        </ul>
    </div>
    <div id="gallery-library-container">
         <a href='http://www.facebook.com/WinslowsBuildings?fref=ts'><img src="/img/winslows/layout/gallery_image.png" /></a >
    </div>
    <div id="gallery-background-container"></div>
</div>    