<div id="gallery-main-container">
    <div id="gallery-header-container-left">
        <div id="gallery-header-content-left">
            <h1>Browse By</h1>
        </div>
    </div>
    <div id="gallery-header-container-right">
        <div id="gallery-header-content-right">
            <h1>Gallery</h1>
        </div>
    </div>
    <div id="gallery-left-navigation">
        <ul>
                <h3>Building Type</h3>
                    <li>Garages</li>
                    <li>Carports</li>
                    <li>Storage</li>
                    <li>Combo</li>
                    <li>Misc<br>(Pets, Live Stock)</li>
                <h3>Use</h3>
                    <li>Auto/Boat/RV</li>
                    <li>Pets</li>
                    <li>Storage</li>
                <h3>Building Material</h3>
                    <li>Metal</li>
                    <li>Wood</li>
        </ul>
    </div>
    <div id="gallery-library-container">
        <div class="grid_element">
<!--         <a href='http://www.facebook.com/WinslowsBuildings?fref=ts'><img src="/img/winslows/layout/gallery_image.png" /></a >-->
            <div class="desc">Garages</div> <br>
                <div class="div-img">
                <a target="_blank" href="garages.html">
                <img src="/img/winslows/gallery/index/metal_garage_7751.png" alt="Metal Garage" width="240" height="140">
                </a>
                </div><br>
            <div class="desc">Garages</div> <br>
                <div class="div-img">
                <a target="_blank" href="storage.htm">
                <img src="/img/winslows/gallery/index/metal_garage_7751.png" alt="Metal Garage" width="240" height="140">
                </a>
                </div><br>
            <div class="desc">Carports</div> <br>
                <div class="div-img">
                <a target="_blank" href="auto/boat/rv.htm">
                <img src="/img/winslows/gallery/index/carport.png" alt="Certified Carport" width="240" height="140">
                </a>
                </div><br>
            <div class="desc">Carports</div> <br>
                <div class="div-img">
                <a target="_blank" href="Pets.htm">
                <img src="/img/winslows/gallery/index/carport.png" alt="Certified Carport" width="240" height="140">
                </a>
                </div>
            <div class="desc">Storage</div> <br>
                <div class="div-img">
                <a target="_blank" href="storage.htm">
                <img src="/img/winslows/gallery/index/wood_barn.png" alt="Wood Barn" width="240" height="140">
                </a>
                </div><br>
                <div class="desc">Storage</div> <br>
                <div class="div-img">
                <a target="_blank" href="storage.htm">
                <img src="/img/winslows/gallery/index/wood_barn.png" alt="Wood Barn" width="240" height="140">
                </a>
                </div><br>
                <div class="desc">Combo</div> <br>
                <div class="div-img">
                <a target="_blank" href="storage.htm">
                <img src="/img/winslows/gallery/index/combo.png" alt="Combo" width="240" height="140">
                </a>
                </div><br>
                <div class="desc">Combo</div> <br>
                <div class="div-img">
                <a target="_blank" href="storage.htm">
                <img src="/img/winslows/gallery/index/combo.png" alt="Combo" width="240" height="140">
                </a>
                </div><br>
                <div class="desc">Pets</div> <br>
                <div class="div-img">
                <a target="_blank" href="Pets.htm">
                <img src="/img/winslows/gallery/index/complete_doghouse.png" alt="Doghouse" width="240" height="140">
                </a>
                </div>
            <div class="desc">Pets</div> <br>
                <div class="div-img">
                <a target="_blank" href="Pets.htm">
                <img src="/img/winslows/gallery/index/complete_doghouse.png" alt="Doghouse" width="240" height="140">
                </a>
                </div>
        </div>
        <div class="grid_element">
<!--         <a href='http://www.facebook.com/WinslowsBuildings?fref=ts'><img src="/img/winslows/layout/gallery_image.png" /></a >-->
            <div class="desc">Garages</div> <br>
                <div class="div-img">
                <a target="_blank" href="garages.html">
                <img src="/img/winslows/gallery/index/metal_garage_7751.png" alt="Metal Garage" width="240" height="140">
                </a>
                </div><br>
            <div class="desc">Garages</div> <br>
                <div class="div-img">
                <a target="_blank" href="storage.htm">
                <img src="/img/winslows/gallery/index/metal_garage_7751.png" alt="Metal Garage" width="240" height="140">
                </a>
                </div><br>
            <div class="desc">Carports</div> <br>
                <div class="div-img">
                <a target="_blank" href="auto/boat/rv.htm">
                <img src="/img/winslows/gallery/index/carport.png" alt="Certified Carport" width="240" height="140">
                </a>
                </div><br>
            <div class="desc">Carports</div> <br>
                <div class="div-img">
                <a target="_blank" href="auto/boat/rv.htm">
                <img src="/img/winslows/gallery/index/carport.png" alt="Certified Carport" width="240" height="140">
                </a>
                </div><br>
            <div class="desc">Storage</div> <br>
                <div class="div-img">
                <a target="_blank" href="storage.htm">
                <img src="/img/winslows/gallery/index/wood_barn.png" alt="Wood Barn" width="240" height="140">
                </a>
                </div><br>
            <div class="desc">Storage</div> <br>
                <div class="div-img">
                <a target="_blank" href="storage.htm">
                <img src="/img/winslows/gallery/index/wood_barn.png" alt="Wood Barn" width="240" height="140">
                </a>
                </div><br>
                <div class="desc">Combo</div> <br>
                <div class="div-img">
                <a target="_blank" href="storage.htm">
                <img src="/img/winslows/gallery/index/combo.png" alt="Combo" width="240" height="140">
                </a>
                </div><br>
                <div class="desc">Combo</div> <br>
                <div class="div-img">
                <a target="_blank" href="storage.htm">
                <img src="/img/winslows/gallery/index/combo.png" alt="Combo" width="240" height="140">
                </a>
                </div><br>
            <div class="desc">Pets</div> <br>
                <div class="div-img">
                <a target="_blank" href="Pets.htm">
                <img src="/img/winslows/gallery/index/complete_doghouse.png" alt="Doghouse" width="240" height="140">
                </a>
                </div>
            <div class="desc">Pets</div> <br>
                <div class="div-img">
                <a target="_blank" href="Pets.htm">
                <img src="/img/winslows/gallery/index/complete_doghouse.png" alt="Doghouse" width="240" height="140">
                </a>
                </div>
        </div>
        <div class="grid_element">
<!--         <a href='http://www.facebook.com/WinslowsBuildings?fref=ts'><img src="/img/winslows/layout/gallery_image.png" /></a >-->
            <div class="desc">Garages</div> <br>
                <div class="div-img">
                <a target="_blank" href="garages.html">
                <img src="/img/winslows/gallery/index/metal_garage_7751.png" alt="Metal Garage" width="240" height="140">
                </a>
                </div><br>
            <div class="desc">Garages</div> <br>
                <div class="div-img">
                <a target="_blank" href="garages.html">
                <img src="/img/winslows/gallery/index/metal_garage_7751.png" alt="Metal Garage" width="240" height="140">
                </a>
                </div><br>
            <div class="desc">Carports</div> <br>
                <div class="div-img">
                <a target="_blank" href="auto/boat/rv.htm">
                <img src="/img/winslows/gallery/index/carport.png" alt="Certified Carport" width="240" height="140">
                </a>
                </div><br>
            <div class="desc">Carports</div> <br>
                <div class="div-img">
                <a target="_blank" href="auto/boat/rv.htm">
                <img src="/img/winslows/gallery/index/carport.png" alt="Certified Carport" width="240" height="140">
                </a>
                </div><br>
            <div class="desc">Storage</div> <br>
                <div class="div-img">
                <a target="_blank" href="storage.htm">
                <img src="/img/winslows/gallery/index/wood_barn.png" alt="Wood Barn" width="240" height="140">
                </a>
                </div><br>
            <div class="desc">Storage</div> <br>
                <div class="div-img">
                <a target="_blank" href="storage.htm">
                <img src="/img/winslows/gallery/index/wood_barn.png" alt="Wood Barn" width="240" height="140">
                </a>
                </div><br>
            <div class="desc">Combo</div> <br>
                <div class="div-img">
                <a target="_blank" href="storage.htm">
                <img src="/img/winslows/gallery/index/combo.png" alt="Combo" width="240" height="140">
                </a>
                </div><br>
            <div class="desc">Combo</div> <br>
                <div class="div-img">
                <a target="_blank" href="storage.htm">
                <img src="/img/winslows/gallery/index/combo.png" alt="Combo" width="240" height="140">
                </a>
                </div><br>
            <div class="desc">Pets</div> <br>
                <div class="div-img">
                <a target="_blank" href="Pets.htm">
                <img src="/img/winslows/gallery/index/complete_doghouse.png" alt="Doghouse" width="240" height="140">
                </a>
                </div>
            <div class="desc">Pets</div> <br>
                <div class="div-img">
                <a target="_blank" href="Pets.htm">
                <img src="/img/winslows/gallery/index/complete_doghouse.png" alt="Doghouse" width="240" height="140">
                </a>
                </div>
        </div>
    </div>
    <div id="gallery-background-container"></div>
</div>    