<?php
if($this->Instance->getProduct()->getDescriminator() != "Configurable")
{
    echo '<script type="text/javascript">parent.location = location</script>';
}
?>
<div id="addproduct2_colorbox_content">..Loading</div>
<script type="text/javascript">
    $.ajax({
	url: "/company/supplier-product-configurable-instance/chooseeditorajax/id/<?php echo $this->Instance->getId();?>",
	success: function(data) { 
	    $.colorbox.resize({width:700,height:400})
	    c = $("#addproduct2_colorbox_content");
	    c.fadeOut('fast', function(){c.html(data).fadeIn('fast')});
	},
	error: function(request,error){
	    alert(request.responseText)
	}
    });
</script>