<?php 
echo($this->flashMessages());
echo "<div>";
echo HTML::backAnchorIcon("Quote - View ", "/lead-quote/view/id/".$this->Quote->getId());
echo "</div>";
/* @var $Quote Entities\Company\Lead\Quote */
$Quote = $this->Quote;
?>
<h1 class="header1">Quote - Sell</h1>
<div class="padded_frame">
    <h3>Total Due Today:</h3>
    <div class="padded_frame">
	<?php echo $Quote->getDueAtSaleTotalPrice()->getDisplayPrice();?>
    </div>
    <h3>Payment Type</h3>
    <?php 
	echo $this->payment_form;
    ?>
</div>
<script type="text/javascript">
    Q = new Quote();
    Q.ApplicationOnClickBind($(".application_edit"));
    Q.ViewItemOnClickBind($(".view_item"));
</script>