<?php 
echo($this->flashMessages()); 
echo "<div>";
echo HTML::backAnchorIcon("Back ", $this->back);
echo "</div>";
?>
<h1 class="header1">Quote - View</h1>
<fieldset class="padded_frame blue_frame">
    <legend>Menu</legend>
<?php
echo HTML::buttonBlue("printer.png", "Print", "quote_print", "margin-right:5px;position:relative;");
echo HTML::buttonBlue("money.png", "Sell", "quote_sell", "position:relative;");
?>
</fieldset>
<?php
/* @var $quote \Entities\Company\Lead\Quote */
$quote		= $this->Quote;
$quote_id	= $quote->getId();
$Items	= $quote->getItems();
?>
<div class="blue_frame bg_blue_fade" style="margin: 20px;margin-bottom: 0px;padding: 5px;">
    <h4 class="no_space" style="color: #2000EE;">
	Info
	<?php
	echo HTML::anchorIcon(
		"pencil.png", 
		"", 
		"/company/lead-quote/edit/id/".$quote_id,
		"margin-left:5px;",
		"Edit Quote"
		);
	?>
    </h4>
    <div>
	Date:<?php echo $quote->getCreated()->format("F j, Y, g:i a"); ?> &nbsp;&nbsp;&nbsp; 
	Lead:<?php echo $quote->getLead()->getFullName(); ?> &nbsp;&nbsp;&nbsp; 
	Sales Person:<?php echo $quote->getEmployee()->getFullName(); ?> &nbsp;&nbsp;&nbsp; 
	Total:$<?php echo number_format($quote->getTotal(), 2); ?> &nbsp;&nbsp;&nbsp;
    </div>
</div>
<div class="padded_frame" style="width: 415px;float: left;padding-top: 0px;">
    <div id="accordion">
	<h3>
	    <a href="#">Items</a>
	    <?php echo HTML::buttonBlue("package_add.png", "Add Item", "quoteproduct_add", "float:right;width:110px;");?>
	</h3>
	<div>
	    <?php
	    echo count($Items)<1 ? "<span class='small gray'>No Items</span>" : "";
	    /* @var $Item \Entities\Company\Lead\Quote\Item */
	    foreach ($Items as $Item)
	    {
		/* @var $Instance \Entities\Company\Supplier\Product\Instance */
		$Instance	    = $Item->getInstance();
		/* @var $InstancePrice Dataservice_Price */
		$InstancePrice	    = $Instance->getPrice();
		$instance_quantity  = $Item->getQuantity();
		?>
		<h4 class="no_space bg_blue_fade blue_frame" style="padding: 3px;margin-bottom: 3px;">
		    <?php 
		    echo $Instance->getProduct()->getName();
		    echo HTML::anchorIcon(
			    "delete.png", 
			    "", 
			    "/company/lead-quote/itemremove/id/".$quote->getId()."/item_id/".$Item->getId(),
			    "float:right;margin-right:5px;vertical-align:bottom;",
			    "Delete Item"
			    );
		    echo HTML::buttonIcon(
			    "pencil.png", 
			    "view_item_".$Item->getId(), 
			    "Edit Item", "quote_item_edit", 
			    "float:right;margin-right:5px;vertical-align:bottom;",
			    'item_id="'.$Item->getId().'"'
			    );
		    echo HTML::buttonIcon(
			    "bullet_arrow_down.png", 
			    "expand_item_".$Item->getId(), 
			    "Show Details", "expand_item", 
			    "float:right;margin-right:5px;vertical-align:bottom;",
			    'item_id="'.$Item->getId().'"'
			    );
		    ?>
		</h4>
		<div style="display: none;border: solid 1px #E5E5E5;" id="item_details_<?php echo $Item->getId();?>">
		    <b>Options</b><br />
		    <?php echo $Instance->getOptionsDisplay();?>
		    <b>Price Details</b><br />
		    <?php echo $InstancePrice->getDisplayDetails();?>
		</div>
		<label>Quantity:</label>
		<div style="display: inline;"><?php echo $instance_quantity; ?></div>
		<br />
		<label>Price Each:</label>
		<div style="display: inline;"><?php echo $InstancePrice->getDisplayPrice(); ?></div>
		<br />
		<label>Price Total:</label>
		<div style="display: inline;">
		    $<?php echo number_format(($instance_quantity * $InstancePrice->getPrice()), 2); ?>
		</div>
		<br />
		<?php
	    }
	    ?>
	</div>
    </div>
</div>
<div class="padded_frame" style="width: 415px;float: right;padding-top: 0px;">
    <h3><a href="#">Documents</a></h3>
    <div>Put Documents here</div>
</div>
<div style="clear: both;"><input type="hidden" id="quote_id" value="<?php echo $quote_id;?>" /></div>
<script type="text/javascript">
    $("#quoteproduct_add").colorbox({href:"/company/lead-quote/productadd1/id/<?php echo $quote_id;?>"});
    Quote = new Quote();
    Quote.EditItemOnClickBind($(".quote_item_edit"));
    Quote.ExpandItemOnClickBind($(".expand_item"));
    Quote.PrintOnClickBind($("#quote_print"));
    Quote.SellOnClickBind($("#quote_sell"));
</script>
