<?php 
echo($this->flashMessages()); 
echo "<div>";
echo HTML::backAnchorIcon("Lead Search", "/lead/search");
echo "</div>";
$lead	= $this->Lead;
$lead_id	= $lead->getId();
$addresses	= $lead->getPersonAddresses();
$phones		= $lead->getPersonPhoneNumbers();
$emails		= $lead->getPersonEmailAddresses();
$contacts	= $lead->getContacts();
?>
<div class="blue_frame bg_blue_fade" style="margin: 20px;margin-bottom: 0px;padding: 5px;">
    <h3 class="no_space" style="color: #2000EE;">Lead Info</h4>
    <div>
	Name:<?php echo $lead->getFullName(); ?> &nbsp;&nbsp;&nbsp; 
	Sales Location:<?php echo $lead->getEmployee()->getLocation()->getName(); ?> &nbsp;&nbsp;&nbsp; 
	Company:<?php echo $lead->getEmployee()->getLocation()->getCompany()->getName(); ?> &nbsp;&nbsp;&nbsp; 
	Salesman:<?php echo $lead->getEmployee()->getFullName(); ?>
    </div>
</div>
<div class="padded_frame" style="width: 415px;float: left;padding-top: 0px;">
    <div id="accordion">
	<h3>
	    <a href="#">Addresses</a>
	    <?php echo HTML::buttonBlue("building_add.png", "Add address", "address_add", "float:right;width:110px;");?>
	</h3>
	<div>
	    <?php
	    echo count($addresses)<1 ? "<span class='small gray'>No Addresses</span>" : "";
	    /* @var $Address \Entities\Address */
	    foreach ($addresses as $Address) {
		?>
		<h4 class="no_space bg_blue_fade blue_frame" style="padding: 3px;margin-bottom: 3px;">
		    <?php 
		    echo $Address->getName();
		    echo HTML::anchorIcon(
			    "pencil.png", 
			    "", 
			    "/lead/editaddress/lead_id/".$lead_id."/address_id/".$Address->getId(),
			    "margin-left:5px;"
			    );
		    ?>
		</h4>
		<label for="addr_1_addr1">Address 1:</label>
		<div id="addr_1_addr1" style="display: inline;"><?php echo $Address->getAddress1(); ?></div><br />
		<label for="addr_1_addr2">Address 2:</label>
		<div id="addr_1_addr2" style="display: inline;"><?php echo $Address->getAddress2(); ?></div><br />
		<label for="addr_1_csz">City/ST/Zip:</label>
		<div id="addr_1_csz" style="display: inline;">
		    <?php 
		    echo $Address->getCity().", ".
			    $Address->getState()." ".
			    $Address->getZip1()."-".
			    $Address->getZip2(); ?>
		</div>
		<?php
	    }
	    ?>
	</div>
	<hr />
	<h3>
	    <a href="#">Phone</a>
	    <?php 
	    echo HTML::buttonBlue(
		    "phone_add.png", 
		    "Add Phone", 
		    "phone_add", "float:right;width:110px;"
		    );?>
	</h3>
	<div>
	    <?php
	    echo count($phones)<1 ? "<span class='small gray'>No Phones</span>" : "";
	    /* @var $PhoneNumber \Entities\PhoneNumber */
	    foreach ($phones as $PhoneNumber) {
		?>
		<h4 class="no_space blue_frame bg_blue_fade" style="padding:3px;margin-bottom: 3px;">
		    <?php 
		    echo $PhoneNumber->getType(); 
		    echo HTML::anchorIcon(
			    "pencil.png", 
			    "", 
			    "/lead/editphone/lead_id/".$lead_id."/phonenumber_id/".
				$PhoneNumber->getId(), 
			    "margin-left:5px;"
			    );
		    ?>
		</h4>
		<label for="phone1">Num:</label>
		<div id="phone1" style="display: inline;">
		    <?php 
		    echo "(".$PhoneNumber->getAreaCode().") ".$PhoneNumber->getNum1()."-".$PhoneNumber->getNum2(); 
		    ?>
		</div><br />
		<label for="ext1">Ext:</label>
		<div id="ext1" style="display: inline;">
		    <?php 
		    echo $PhoneNumber->getExtension(); 
		    ?>
		</div>
		<?php
	    }
	    ?>
	</div>
	<hr />
	<h3>
	    <a href="#">Email</a>
	    <?php 
	    echo HTML::buttonBlue(
		    "email_add.png", 
		    "Add Email", 
		    "email_add", "float:right;width:110px;"
		    );?>
	</h3>
	<div>
	    <?php
	    /* @var $Emailaddress \Entities\Emailaddress */
	    foreach ($emails as $Emailaddress) {
		?>
		<h4 class="no_space bg_blue_fade blue_frame" style="padding: 3px;margin-bottom: 3px;">
		    <?php 
		    echo $Emailaddress->getType(); 
		    echo HTML::anchorIcon(
			    "pencil.png", 
			    "", 
			    "/lead/editemail/lead_id/".$lead_id."/emailaddress_id/".
				$Emailaddress->getId(), 
			    "margin-left:5px;"
			    );
		    ?>
		</h4>
		<label>Address:</label>
		<div style="display: inline;">
		    <?php 
		    echo $Emailaddress->getAddress(); 
		    ?>
		</div>
		<?php
	    }
	    ?>
	</div>
    </div>
</div>
<div class="padded_frame" style="width: 415px;float: right;padding-top: 0px;">
    <h3>
	<a href="#">Contacts</a>
	<span style="float:right;">
	    <select id="contact_type_id_select">
		<option class="gray small" value="">Choose contact medium</option>
		<?php 
		foreach($this->Locations as $Location){
		    echo "<option type_string='location' value='".$Location->getId()."'>Walk In: ".$Location->getName()."</option>";
		}
		foreach($phones as $PhoneNumber){
		    echo "<option type_string='phone' value='".$PhoneNumber->getId()."'>Phone: ".$PhoneNumber->getNumberDisplay()."</option>";
		}
		foreach($emails as $Emailaddress){
		    echo "<option type_string='email' value='".$Emailaddress->getId()."'>Email: ".$Emailaddress->getAddress()."</option>";
		}
		?>
	    </select>
	    <?php 
	    echo HTML::buttonBlue(
		    "phone_sound.png", 
		    "Add Contact", 
		    "contact_add", 
		    "contact_add", 
		    "padding-left:3px;"
		    );?>
	</span>
    </h3>
    <div>
	<div style="max-height: 300px;overflow: auto;">
	    <?php
	    /* @var $Contact \Entities\Contact */
	    foreach ($contacts as $Contact) {
		?>
		<h4 class="no_space bg_blue_fade blue_frame" style="padding:3px;margin-bottom: 3px;">
		    <?php 
		    echo $Contact->getCreated()->format("m-d-Y, g:i a")." - ".$Contact->getPerson()->getFullName(); 
		    echo HTML::anchorIcon(
			    "pencil.png", 
			    "", 
			    "/lead/editcontact/lead_id/".$lead_id."/contact_id/".
				$Contact->getId(), 
			    "margin-left:5px;"
			    );
		    ?>
		</h4>
		<label>Type:</label>
		<div style="display: inline;">
		    <?php 
		    echo $Contact->getTypeDisplay()." - ".$Contact->getTypeDetail(); 
		    ?>
		</div><br />
		<label>Note:</label>
		<div style="display: inline;">
		    <?php 
		    echo HTML::truncateString($Contact->getNote(), 40);
		    ?>
		</div><br />
		<label>Result:</label>
		<div style="display: inline;">
		    <?php 
		    echo $Contact->getResultDisplay();
		    ?>
		</div><br /><br />
		<?php
	    }
	    ?>
	</div>
    </div>
    <hr />
    <h3><a href="#">Documents</a></h3>
    <div>Put Documents here</div>
</div>
<div style="clear: both;"><input type="hidden" id="lead_id" value="<?php echo $lead_id;?>" /></div>
<script type="text/javascript">
    Lead = new Lead();
    Lead.AddPhoneClickBind("phone_add");
    Lead.AddAddressClickBind("address_add");
    Lead.AddEmailClickBind("email_add");
    Lead.AddContactClickBind("contact_add");
</script>
