<?php echo($this->flashMessages()); ?>
<h1 class="header1">Dealers - View All</h1>
<fieldset class="padded_frame blue_frame">
    <legend>Menu</legend>
    <?php
    echo HTML::buttonBlue("add.png", "Add Dealer", "add_dealer", "position:relative;");
    ?>
</fieldset>
<fieldset class="padded_frame blue_frame">
    <legend>Dealers</legend>
    <?php
    /* @var $Dealer \Entities\Company\Dealer */
    foreach($this->Dealers as $Dealer){
	echo "<div dealer_id='".$Dealer->getId()."'>";
	echo HTML::buttonIcon(
		"bullet_go.png", 
		"edit_dealer_".$Dealer->getId(), 
		"Edit Dealer", 
		"edit_dealer", 
		"padding-right:5px;"
		);
	echo ":: ";
	echo $Dealer->getName()." - ".$Dealer->getDba();
    }
    ?>
</fieldset>
<script type="text/javascript">
    Company_Dealer = new Dealer();
    Company_Dealer.AddOnclickBind($("#add_dealer"));
    Company_Dealer.EditOnclickBind($(".edit_dealer"));
</script>