<?php 
use Dataservice\Html\CRUD;

echo($this->flashMessages()); 

echo CRUD\Header::factory("Dealer - View")->getHtml();

/* @var $Dealer \Entities\Company\Dealer */
$Dealer	= $this->Dealer;

CRUD\Body::factory()->start();

CRUD\Tabs::factory()
	->addEntityViewTab("Information", $Dealer)
	->addRelationshipViewTab($Dealer, "Company")
	->addRelationshipViewTab($Dealer, "Locations")
	->render();

CRUD\Body::factory()->end();

echo CRUD\Tabs::factory()->getJS();