<?php echo($this->flashMessages()); ?>
<h1 class="header1">Configurable Product Option Parameter Values - View All</h1>
<fieldset class="padded_frame blue_frame">
    <legend>Menu</legend>
    <?php
    echo HTML::buttonBlue("add.png", "Add Value", "value_add", "position:relative;");
    ?>
</fieldset>
<fieldset class="padded_frame blue_frame">
    <legend>Values</legend>
    <?php
    /* @var $Value \Entities\Company\Supplier\Product\Configurable\Option\ParameterValue */
    foreach($this->Values as $Value){
	echo "<div value_id='".$Value->getId()."'>";
	echo HTML::buttonIcon(
		"pencil.png", 
		"value_edit_".$Value->getId(), 
		"Edit Value", 
		"value_edit", 
		"padding-right:5px;"
		);
	echo HTML::buttonIcon(
		"delete.png", 
		"value_delete_".$Value->getId(), 
		"Delete Value", 
		"value_delete", 
		"padding-right:5px;"
		);
	echo ":: ";
	echo $Value->getName();
	
	$Parameter  = $Value->getParameter();
	$Option	    = $Parameter->getOption();
	
	if($Parameter)echo "<span class='gray small'> - ".$Option->getName ()." - ".$Parameter->getName()."</span>";
	else echo " <span class='error_message'>No Option</span>";
	echo "</div>";
    }
    ?>
</fieldset>
<script type="text/javascript">
    Value = new Value();
    Value.AddOnclickBind($("#value_add"));
    Value.EditOnclickBind($(".value_edit"));
    Value.DeleteOnclickBind($(".value_delete"));
</script>