<?php 
echo($this->flashMessages()); 
echo "<div>";
echo \Dataservice\Html\Anchor::backAnchorIcon("Supplier - view", "/supplier/view/id/".$this->Product->getSupplier()->getId());
echo "</div>";
?>
<h1 class="header1">Product - View</h1>
<?php
/* @var $Product \Entities\Company\Supplier\Product\ProductAbstract */
$Product	= $this->Product;
$product_id	= $Product->getId();
$Categories	= $Product->getCategories();
$DeliveryTypes	= $Product->getDeliveryTypes();
$Purposes	= $Product->getPurposes();
$Images		= $Product->getImages();
$Options	= null;
$price		= null;
$className	= null;

switch ($Product->getDescriminator()) 
{
    case "Configurable":
	/* @var $Product \Entities\Company\Supplier\Product\Configurable */
	$Options	= $Product->getOptions();
	$className	= $Product->getClassName();
    break;
    case "Simple":
	/* @var $Product \Entities\SimpleProduct */
	$price		= $Product->getPrice()->getDisplayPrice();
    break;
}
?>
<div class="blue_frame bg_blue_fade" style="margin: 20px;margin-bottom: 0px;padding: 5px;">
    <h3 class="no_space" style="color: #2000EE;">
	Info
	<?php
	echo \Dataservice\Html\Anchor::anchorIcon(
		"pencil.png", 
		"", 
		"/supplier-product/edit/id/".$product_id,
		"margin-left:5px;"
		);
	?>
    </h4>
    <div>
	<label>Type:</label> <?php echo $Product->getDescriminator(); ?> &nbsp;&nbsp;&nbsp;
	<label>Name:</label> <?php echo $Product->getName(); ?> &nbsp;&nbsp;&nbsp;
	<label>Part#:</label> <?php echo $Product->getPartNumber(); ?> &nbsp;&nbsp;&nbsp;
	<label>Supplier:</label> <?php echo $Product->getSupplier()->getName(); ?> <br />
	<label>Description:</label> <span class="small"><?php echo $Product->getDescription(); ?></span><br />
	<?php
	if($className){?><label>Class Name:</label> <?php echo $className; ?> &nbsp;&nbsp;&nbsp;<?php }
	if($price){?><label>Price:</label> <?php echo $price; ?> &nbsp;&nbsp;&nbsp;<?php }
	?>
    </div>
</div>
<div class="padded_frame" style="width: 415px;float: left;padding-top: 0px;">
    <div id="accordion">
	<h3>
	    <a href="#">Categories</a>
	    <?php 
	    echo \Dataservice\Html\Button::buttonBlue(
		    "text_list_bullets.png",
		    "Manage",
		    "categories_manage",
		    "float:right;width:80px;"
		    );
	    echo \Dataservice\Html\Button::buttonBlue(
		    "add.png",
		    "Add New",
		    "category_add",
		    "float:right;width:80px;margin-right:5px;"
		    );
	    ?>
	</h3>
	<div>
	    <ul>
	    <?php
	    /* @var $Category \Entities\Company\Supplier\Product\Category */
	    if(count($Categories) > 0)
	    {
		foreach ($Categories as $Category)
		{
		    ?>
		    <li>
			<?php
			echo \Dataservice\Html\Anchor::anchorIcon(
				"bullet_go.png", 
				"", 
				"/supplier-product-category/view/id/".$Category->getId(),
				"margin-left:5px;"
				);
			echo $Category->getNameWithParentsString();
			?>
		    </li>
		    <?php
		}
	    }
	    else echo "<li>No Categories</li>";
	    ?>
	    </ul>
	</div>
	<hr />
	<?php
	if($Options)
	{
	    ?>
	    <h3>
		<a href="#">Option Groups</a>
		<?php 
		echo \Dataservice\Html\Button::buttonBlue(
			"text_list_bullets.png", 
			"Manage", 
			"groups_manage", 
			"float:right;width:80px;"
			);
		echo \Dataservice\Html\Button::buttonBlue(
			"add.png", 
			"Add New", 
			"group_add", 
			"float:right;width:80px;margin-right:5px;"
			);
		?>
	    </h3>
	    <div>
		<ul>
		<?php
		/* @var $CbOption \Entities\CbOption */
		if(count($Options)>0){
		    foreach ($Options as $Option) {
			?>
			<li>
			    <?php
			    echo \Dataservice\Html\Anchor::anchorIcon(
				    "bullet_go.png", 
				    "", 
				    "/supplier-product-configurable-option/view/id/".$Option->getId(),
				    "margin-left:5px;"
				    );
			    echo $Option->getName();
			    ?>
			</li>
			<?php
		    }
		}
		else echo "<li>No Options</li>";
		?>
		</ul>
	    </div>
	    <hr />
	    <?php
	}
	?>
    </div>
</div>
<div class="padded_frame" style="width: 415px;float: right;padding-top: 0px;">
    <h3>
	<a href="#">Delivery Types</a>
	<?php 
	echo \Dataservice\Html\Button::buttonBlue(
		"text_list_bullets.png",
		"Manage",
		"delivery_types_manage",
		"float:right;width:80px;"
		);
	echo \Dataservice\Html\Button::buttonBlue(
		"add.png",
		"Add New",
		"delivery_type_add",
		"float:right;width:80px;margin-right:5px;"
		);
	?>
    </h3>
    <div>
	<ul>
	<?php
	/* @var $DeliveryType \Entities\Company\Supplier\Product\DeliveryType\DeliveryTypeAbstract */
	if(count($DeliveryTypes) > 0)
	{
	    foreach ($DeliveryTypes as $DeliveryType)
	    {
		?>
		<li>
		    <?php
		    echo \Dataservice\Html\Anchor::anchorIcon(
			    "bullet_go.png", 
			    "", 
			    "/supplier-product-delivery-type/view/id/".$DeliveryType->getId(),
			    "margin-left:5px;"
			    );
		    echo $DeliveryType->getName();
		    ?>
		</li>
		<?php
	    }
	}
	else echo "<li>No Delivery Types</li>";
	?>
	</ul>
    </div>
    <hr />
    <h3>
	<a href="#">Purposes</a>
	<?php 
	echo \Dataservice\Html\Button::buttonBlue(
		"add.png",
		"Add Purpose",
		"purpose_add",
		"float:right;margin-right:5px;"
		);
	?>
    </h3>
    <div>
	<ul>
	<?php
	/* @var $Purpose \Entities\Company\Supplier\Product\Purpose */
	if(count($Purposes) > 0)
	{
	    foreach ($Purposes as $Purpose)
	    {
		?>
		<li>
		    <?php
		    echo \Dataservice\Html\Anchor::anchorIcon(
			    "bullet_go.png", 
			    "", 
			    "/supplier-product-purpose/edit/id/".$Purpose->getId(),
			    "margin-left:5px;"
			    );
		    echo $Purpose->getName();
		    ?>
		</li>
		<?php
	    }
	}
	else echo "<li>No Purposes</li>";
	?>
	</ul>
    </div>
    <hr />
    <h3><a href="#">Documents</a></h3>
    <div>Put Documents here</div>
    <hr />
    <h3>
	<a href="#">Images</a>
	<?php 
	echo \Dataservice\Html\Button::buttonBlue(
		"add.png",
		"Add Image",
		"image_add",
		"float:right;margin-right:5px;"
		);
	?>
    </h3>
    <div>
	<ul>
	<?php
	/* @var $Image \Entities\Company\Supplier\Product\File\Image */
	if(count($Images) > 0)
	{
	    foreach ($Images as $Image)
	    {
		?>
		<li>
		    <?php
//		    echo \Dataservice\Html\Anchor::anchorIcon(
//			    "bullet_go.png", 
//			    "", 
//			    "/supplier-product-file-image/edit/id/".$Image->getId(),
//			    "margin-left:5px;"
//			    );
//		    echo $Image->getName();
		    echo \Services\File\Image::factory()->getHtmlThumbImg($Image);
		    ?>
		</li>
		<?php
	    }
	}
	else echo "<li>No Images</li>";
	?>
	</ul>
    </div>
</div>
<div style="clear: both;"><input type="hidden" id="product_id" value="<?php echo $product_id;?>" /></div>
<script type="text/javascript">
    Product = new Product();
    Product.ManageOptionGroupsOnclickBind($("#groups_manage"));
    Product.OptionGroupAddOnclickBind($("#group_add"));
    Product.ManageCategoriesOnclickBind($("#categories_manage"));
    Product.CategoryAddOnclickBind($("#category_add"));
    Product.ManageDeliveryTypesOnclickBind($("#delivery_types_manage"));
    Product.DeliveryTypeAddOnclickBind($("#delivery_type_add"));
    Product.PurposeAddOnclickBind($("#purpose_add"));
    Product.ImageAddOnclickBind($("#image_add"));
</script>