<?php 
use Dataservice\Html\CRUD;

echo($this->flashMessages()); 

echo CRUD\Header::factory("Employee Address - View")->getHtml();

$Address = $this->Address;

CRUD\Body::factory()->start();

CRUD\Tabs::factory()
	->addEntityViewTab("Information", $Address)
	->addRelationshipViewTab($Address, "Employee")
	->addRelationshipViewTab($Address, "Contacts")
	->render();

CRUD\Body::factory()->end();

echo CRUD\Tabs::factory()->getJS();