<iframe id="builder_frame" width="100%" height="1200" src="http://<?php echo $_SERVER["SERVER_NAME"];?>/builder" style="border: none;overflow: hidden;"></iframe>
<script type="text/javascript">
    setTimeout(function(){
	$('#builder_frame').contents().find('#buy_now_button').click(function(){
	    alert($('#builder_frame').contents().find("#builder_code").html());
	});
    },3000);
</script>