<?php
echo($this->flashMessages()); 
?>
<fieldset class="padded_frame blue_frame">
    <legend>Menu</legend>
<?php
echo HTML::buttonBlue("add.png", "Add Option", "option_add", "position:relative;");
echo HTML::buttonBlue("bullet_toggle_plus.png", "Show All", "show_all", "position:relative;margin-left:8px;");
echo HTML::buttonBlue("bullet_toggle_minus.png", "Hide All", "hide_all", "position:relative;margin-left:8px;");
?>
</fieldset>
<fieldset class="padded_frame blue_frame">
    <legend>Options</legend>
    <ol>
    <?php
    /* @var $option \Entities\CbOption */
    foreach($this->options as $option){
	?>
	<li option_id="<?php echo $option->getId();?>"> 
	    <?php 
	    echo HTML::buttonIcon("bullet_wrench.png", "option_edit", "Edit Option Details", "option_edit", "padding-right:5px;");
	    echo HTML::buttonIcon("bullet_add.png", "value_add", "Add Value to Option", "value_add", "padding-right:5px;");
	    echo HTML::buttonIcon("bullet_arrow_down.png", "value_show", "Show Value Options", "value_show", "padding-right:5px;");
	    echo $option->getCode()." - ".$option->getIndex()." - ".$option->getName();
	    ?>
	    <span class="gray small"><?php echo HTML::truncateString($option->getDescription(), 200);?></span>
	    <fieldset id="values_container_<?php echo $option->getId();?>" style="display: none;" class="no_border">
		<legend>Values:</legend>
		    <?php
		    /* @var $value \Entities\CbValue */
		    $values = $option->getValues();
		    if($values && count($values) > 0){
			?><ol><?php
			foreach ($values as $value) {
			    ?>
			    <li value_id="<?php echo $value->getId();?>">
				<?php 
				echo HTML::buttonIcon("bullet_wrench.png", "value_edit", "Edit Value", "value_edit", "padding-right:5px;");
				echo HTML::buttonIcon("bullet_add.png", "valueoption_add", "Add Value Option to Value", "valueoption_add", "padding-right:5px;");
				echo HTML::buttonIcon("bullet_delete.png", "value_delete", "Delete Value", "value_delete", "padding-right:5px;");
				echo $value->getId()."-".$value->getIndex()." - ".$value->getName();
				?>
				<span class="gray small"><?php echo HTML::truncateString($value->getDescription(), 200);?></span>
				<fieldset id="values_option_container_<?php echo $option->getId();?>" class="no_border" >
				<legend>Value Options:</legend>
				<ul>
				    <?php
				    /* @var $value \Entities\CbValue */
				    $valueoptions = $value->getValueOptions();
				    if($valueoptions && count($valueoptions) > 0){
					?><ol><?php
					foreach ($valueoptions as $valueoption) {
					    ?>
					    <li valueoption_id="<?php echo $valueoption->getId();?>">
						<?php 
						echo HTML::buttonIcon("font.png", "valueoption_edit", "Edit Value Option", "valueoption_edit", "padding-right:5px;");
						echo HTML::buttonIcon("font_delete.png", "valueoption_delete", "Delete Value Option", "valueoption_delete", "padding-right:5px;");
						echo $valueoption->getCode()."-".$valueoption->getIndex()." - ".$valueoption->getName();
						?>
						<span class="gray small"><?php echo HTML::truncateString($valueoption->getDescription(), 100);?></span>
					    </li>
					    <?php
					}
					?></ol><?php
				    }
				    else{
					echo " <li>No Value Options</li>";
				    }
				    ?>
				</ul>
				</fieldset>
			    </li>
			    <?php
			}
			?></ol><?php
		    }
		    else{
			echo " No Values";
		    }
		    ?>
	    </fieldset>
	</li>
	<?php
    }
    ?>
    </ol>
</fieldset>
<script type="text/javascript">
    Option = new Option();
    Option.AddOnclickBind($("#option_add"));
    Option.EditOnclickBind($(".option_edit"));
    Option.AddValueOnclickBind($(".value_add"));
    Option.AddValueOptionOnclickBind($(".valueoption_add"));
    Option.ShowValueOnclickBind($(".value_show"));
    Option.ShowAllOnclickBind($("#show_all"));
    Option.HideAllOnclickBind($("#hide_all"));
    Option.EditValueOnclickBind($(".value_edit"));
    Option.DeleteValueOnclickBind($(".value_delete"));
    Option.EditValueOptionOnclickBind($(".valueoption_edit"));
    Option.DeleteValueOptionOnclickBind($(".valueoption_delete"));
</script>